ALPODSclassifierV2=function(Data,Header=NULL){
# V =  ALPODSclassifierV2 (Data,Header)
 # RuleCls=V$RuleCls;PopulationNumber=V$PopulationNumber;Indlist=V$Indlist;
 # rule based classifier and subpopulations corresponding to RuleCls
 # INPUT # Data[1:d,1:n]        data array of d cases with n variables
 # Optional
 # Header[1:d]          Header of data if given, otherwise colnames(Data) per default
 # OUTPUT
 # List V of
 # RuleCls[1:n]             vector of classes, n integer numbers, number k indicates class_k of k number of classes used for training the tree
 # PopulationNumber[1:n]    vector of classes, d integer numbers, number i indicates subpopulation_i of m subpupulations equal to the m leafs of the tree
 # Indlist[1:m]             list of inds for each population such that RuleCls[Indlist[[i]]] = class_k and PopulationNumber[Indlist[[i]]]=subpopulation_i 
 # 
 # V 2.0 generated by XAI ALPODS in R
 # generated by ALPODSgeneration.R
RulePopNumber = rep(0,nrow(Data));RuleCls = rep(0,nrow(Data));
if(!is.null(Header))
   colnames(Data)=Header
 
SS = Data[,'SS']
FS = Data[,'FS']
HLA_DR = Data[,'HLA_DR']
CD7 = Data[,'CD7']
CD56 = Data[,'CD56']
CD45 = Data[,'CD45']
CD34 = Data[,'CD34']
CD33 = Data[,'CD33']
CD13 = Data[,'CD13']
CD117 = Data[,'CD117']
SS..a0.25..FS = Data[,'SS..a0.25..FS']
SS..a0.25..HLA_DR = Data[,'SS..a0.25..HLA_DR']
SS..a0.25..CD7 = Data[,'SS..a0.25..CD7']
SS..a0.25..CD56 = Data[,'SS..a0.25..CD56']
SS..a0.25..CD45 = Data[,'SS..a0.25..CD45']
SS..a0.25..CD34 = Data[,'SS..a0.25..CD34']
SS..a0.25..CD33 = Data[,'SS..a0.25..CD33']
SS..a0.25..CD13 = Data[,'SS..a0.25..CD13']
SS..a0.25..CD117 = Data[,'SS..a0.25..CD117']
FS..a0.25..HLA_DR = Data[,'FS..a0.25..HLA_DR']
FS..a0.25..CD7 = Data[,'FS..a0.25..CD7']
FS..a0.25..CD56 = Data[,'FS..a0.25..CD56']
FS..a0.25..CD45 = Data[,'FS..a0.25..CD45']
FS..a0.25..CD34 = Data[,'FS..a0.25..CD34']
FS..a0.25..CD33 = Data[,'FS..a0.25..CD33']
FS..a0.25..CD13 = Data[,'FS..a0.25..CD13']
FS..a0.25..CD117 = Data[,'FS..a0.25..CD117']
HLA_DR..a0.25..CD7 = Data[,'HLA_DR..a0.25..CD7']
HLA_DR..a0.25..CD56 = Data[,'HLA_DR..a0.25..CD56']
HLA_DR..a0.25..CD45 = Data[,'HLA_DR..a0.25..CD45']
HLA_DR..a0.25..CD34 = Data[,'HLA_DR..a0.25..CD34']
HLA_DR..a0.25..CD33 = Data[,'HLA_DR..a0.25..CD33']
HLA_DR..a0.25..CD13 = Data[,'HLA_DR..a0.25..CD13']
HLA_DR..a0.25..CD117 = Data[,'HLA_DR..a0.25..CD117']
CD7..a0.25..CD56 = Data[,'CD7..a0.25..CD56']
CD7..a0.25..CD45 = Data[,'CD7..a0.25..CD45']
CD7..a0.25..CD34 = Data[,'CD7..a0.25..CD34']
CD7..a0.25..CD33 = Data[,'CD7..a0.25..CD33']
CD7..a0.25..CD13 = Data[,'CD7..a0.25..CD13']
CD7..a0.25..CD117 = Data[,'CD7..a0.25..CD117']
CD56..a0.25..CD45 = Data[,'CD56..a0.25..CD45']
CD56..a0.25..CD34 = Data[,'CD56..a0.25..CD34']
CD56..a0.25..CD33 = Data[,'CD56..a0.25..CD33']
CD56..a0.25..CD13 = Data[,'CD56..a0.25..CD13']
CD56..a0.25..CD117 = Data[,'CD56..a0.25..CD117']
CD45..a0.25..CD34 = Data[,'CD45..a0.25..CD34']
CD45..a0.25..CD33 = Data[,'CD45..a0.25..CD33']
CD45..a0.25..CD13 = Data[,'CD45..a0.25..CD13']
CD45..a0.25..CD117 = Data[,'CD45..a0.25..CD117']
CD34..a0.25..CD33 = Data[,'CD34..a0.25..CD33']
CD34..a0.25..CD13 = Data[,'CD34..a0.25..CD13']
CD34..a0.25..CD117 = Data[,'CD34..a0.25..CD117']
CD33..a0.25..CD13 = Data[,'CD33..a0.25..CD13']
CD33..a0.25..CD117 = Data[,'CD33..a0.25..CD117']
CD13..a0.25..CD117 = Data[,'CD13..a0.25..CD117']
SS..a0.33..FS = Data[,'SS..a0.33..FS']
SS..a0.33..HLA_DR = Data[,'SS..a0.33..HLA_DR']
SS..a0.33..CD7 = Data[,'SS..a0.33..CD7']
SS..a0.33..CD56 = Data[,'SS..a0.33..CD56']
SS..a0.33..CD45 = Data[,'SS..a0.33..CD45']
SS..a0.33..CD34 = Data[,'SS..a0.33..CD34']
SS..a0.33..CD33 = Data[,'SS..a0.33..CD33']
SS..a0.33..CD13 = Data[,'SS..a0.33..CD13']
SS..a0.33..CD117 = Data[,'SS..a0.33..CD117']
FS..a0.33..HLA_DR = Data[,'FS..a0.33..HLA_DR']
FS..a0.33..CD7 = Data[,'FS..a0.33..CD7']
FS..a0.33..CD56 = Data[,'FS..a0.33..CD56']
FS..a0.33..CD45 = Data[,'FS..a0.33..CD45']
FS..a0.33..CD34 = Data[,'FS..a0.33..CD34']
FS..a0.33..CD33 = Data[,'FS..a0.33..CD33']
FS..a0.33..CD13 = Data[,'FS..a0.33..CD13']
FS..a0.33..CD117 = Data[,'FS..a0.33..CD117']
HLA_DR..a0.33..CD7 = Data[,'HLA_DR..a0.33..CD7']
HLA_DR..a0.33..CD56 = Data[,'HLA_DR..a0.33..CD56']
HLA_DR..a0.33..CD45 = Data[,'HLA_DR..a0.33..CD45']
HLA_DR..a0.33..CD34 = Data[,'HLA_DR..a0.33..CD34']
HLA_DR..a0.33..CD33 = Data[,'HLA_DR..a0.33..CD33']
HLA_DR..a0.33..CD13 = Data[,'HLA_DR..a0.33..CD13']
HLA_DR..a0.33..CD117 = Data[,'HLA_DR..a0.33..CD117']
CD7..a0.33..CD56 = Data[,'CD7..a0.33..CD56']
CD7..a0.33..CD45 = Data[,'CD7..a0.33..CD45']
CD7..a0.33..CD34 = Data[,'CD7..a0.33..CD34']
CD7..a0.33..CD33 = Data[,'CD7..a0.33..CD33']
CD7..a0.33..CD13 = Data[,'CD7..a0.33..CD13']
CD7..a0.33..CD117 = Data[,'CD7..a0.33..CD117']
CD56..a0.33..CD45 = Data[,'CD56..a0.33..CD45']
CD56..a0.33..CD34 = Data[,'CD56..a0.33..CD34']
CD56..a0.33..CD33 = Data[,'CD56..a0.33..CD33']
CD56..a0.33..CD13 = Data[,'CD56..a0.33..CD13']
CD56..a0.33..CD117 = Data[,'CD56..a0.33..CD117']
CD45..a0.33..CD34 = Data[,'CD45..a0.33..CD34']
CD45..a0.33..CD33 = Data[,'CD45..a0.33..CD33']
CD45..a0.33..CD13 = Data[,'CD45..a0.33..CD13']
CD45..a0.33..CD117 = Data[,'CD45..a0.33..CD117']
CD34..a0.33..CD33 = Data[,'CD34..a0.33..CD33']
CD34..a0.33..CD13 = Data[,'CD34..a0.33..CD13']
CD34..a0.33..CD117 = Data[,'CD34..a0.33..CD117']
CD33..a0.33..CD13 = Data[,'CD33..a0.33..CD13']
CD33..a0.33..CD117 = Data[,'CD33..a0.33..CD117']
CD13..a0.33..CD117 = Data[,'CD13..a0.33..CD117']
SS..a0.5..FS = Data[,'SS..a0.5..FS']
SS..a0.5..HLA_DR = Data[,'SS..a0.5..HLA_DR']
SS..a0.5..CD7 = Data[,'SS..a0.5..CD7']
SS..a0.5..CD56 = Data[,'SS..a0.5..CD56']
SS..a0.5..CD45 = Data[,'SS..a0.5..CD45']
SS..a0.5..CD34 = Data[,'SS..a0.5..CD34']
SS..a0.5..CD33 = Data[,'SS..a0.5..CD33']
SS..a0.5..CD13 = Data[,'SS..a0.5..CD13']
SS..a0.5..CD117 = Data[,'SS..a0.5..CD117']
FS..a0.5..HLA_DR = Data[,'FS..a0.5..HLA_DR']
FS..a0.5..CD7 = Data[,'FS..a0.5..CD7']
FS..a0.5..CD56 = Data[,'FS..a0.5..CD56']
FS..a0.5..CD45 = Data[,'FS..a0.5..CD45']
FS..a0.5..CD34 = Data[,'FS..a0.5..CD34']
FS..a0.5..CD33 = Data[,'FS..a0.5..CD33']
FS..a0.5..CD13 = Data[,'FS..a0.5..CD13']
FS..a0.5..CD117 = Data[,'FS..a0.5..CD117']
HLA_DR..a0.5..CD7 = Data[,'HLA_DR..a0.5..CD7']
HLA_DR..a0.5..CD56 = Data[,'HLA_DR..a0.5..CD56']
HLA_DR..a0.5..CD45 = Data[,'HLA_DR..a0.5..CD45']
HLA_DR..a0.5..CD34 = Data[,'HLA_DR..a0.5..CD34']
HLA_DR..a0.5..CD33 = Data[,'HLA_DR..a0.5..CD33']
HLA_DR..a0.5..CD13 = Data[,'HLA_DR..a0.5..CD13']
HLA_DR..a0.5..CD117 = Data[,'HLA_DR..a0.5..CD117']
CD7..a0.5..CD56 = Data[,'CD7..a0.5..CD56']
CD7..a0.5..CD45 = Data[,'CD7..a0.5..CD45']
CD7..a0.5..CD34 = Data[,'CD7..a0.5..CD34']
CD7..a0.5..CD33 = Data[,'CD7..a0.5..CD33']
CD7..a0.5..CD13 = Data[,'CD7..a0.5..CD13']
CD7..a0.5..CD117 = Data[,'CD7..a0.5..CD117']
CD56..a0.5..CD45 = Data[,'CD56..a0.5..CD45']
CD56..a0.5..CD34 = Data[,'CD56..a0.5..CD34']
CD56..a0.5..CD33 = Data[,'CD56..a0.5..CD33']
CD56..a0.5..CD13 = Data[,'CD56..a0.5..CD13']
CD56..a0.5..CD117 = Data[,'CD56..a0.5..CD117']
CD45..a0.5..CD34 = Data[,'CD45..a0.5..CD34']
CD45..a0.5..CD33 = Data[,'CD45..a0.5..CD33']
CD45..a0.5..CD13 = Data[,'CD45..a0.5..CD13']
CD45..a0.5..CD117 = Data[,'CD45..a0.5..CD117']
CD34..a0.5..CD33 = Data[,'CD34..a0.5..CD33']
CD34..a0.5..CD13 = Data[,'CD34..a0.5..CD13']
CD34..a0.5..CD117 = Data[,'CD34..a0.5..CD117']
CD33..a0.5..CD13 = Data[,'CD33..a0.5..CD13']
CD33..a0.5..CD117 = Data[,'CD33..a0.5..CD117']
CD13..a0.5..CD117 = Data[,'CD13..a0.5..CD117']
SS..a0.67..FS = Data[,'SS..a0.67..FS']
SS..a0.67..HLA_DR = Data[,'SS..a0.67..HLA_DR']
SS..a0.67..CD7 = Data[,'SS..a0.67..CD7']
SS..a0.67..CD56 = Data[,'SS..a0.67..CD56']
SS..a0.67..CD45 = Data[,'SS..a0.67..CD45']
SS..a0.67..CD34 = Data[,'SS..a0.67..CD34']
SS..a0.67..CD33 = Data[,'SS..a0.67..CD33']
SS..a0.67..CD13 = Data[,'SS..a0.67..CD13']
SS..a0.67..CD117 = Data[,'SS..a0.67..CD117']
FS..a0.67..HLA_DR = Data[,'FS..a0.67..HLA_DR']
FS..a0.67..CD7 = Data[,'FS..a0.67..CD7']
FS..a0.67..CD56 = Data[,'FS..a0.67..CD56']
FS..a0.67..CD45 = Data[,'FS..a0.67..CD45']
FS..a0.67..CD34 = Data[,'FS..a0.67..CD34']
FS..a0.67..CD33 = Data[,'FS..a0.67..CD33']
FS..a0.67..CD13 = Data[,'FS..a0.67..CD13']
FS..a0.67..CD117 = Data[,'FS..a0.67..CD117']
HLA_DR..a0.67..CD7 = Data[,'HLA_DR..a0.67..CD7']
HLA_DR..a0.67..CD56 = Data[,'HLA_DR..a0.67..CD56']
HLA_DR..a0.67..CD45 = Data[,'HLA_DR..a0.67..CD45']
HLA_DR..a0.67..CD34 = Data[,'HLA_DR..a0.67..CD34']
HLA_DR..a0.67..CD33 = Data[,'HLA_DR..a0.67..CD33']
HLA_DR..a0.67..CD13 = Data[,'HLA_DR..a0.67..CD13']
HLA_DR..a0.67..CD117 = Data[,'HLA_DR..a0.67..CD117']
CD7..a0.67..CD56 = Data[,'CD7..a0.67..CD56']
CD7..a0.67..CD45 = Data[,'CD7..a0.67..CD45']
CD7..a0.67..CD34 = Data[,'CD7..a0.67..CD34']
CD7..a0.67..CD33 = Data[,'CD7..a0.67..CD33']
CD7..a0.67..CD13 = Data[,'CD7..a0.67..CD13']
CD7..a0.67..CD117 = Data[,'CD7..a0.67..CD117']
CD56..a0.67..CD45 = Data[,'CD56..a0.67..CD45']
CD56..a0.67..CD34 = Data[,'CD56..a0.67..CD34']
CD56..a0.67..CD33 = Data[,'CD56..a0.67..CD33']
CD56..a0.67..CD13 = Data[,'CD56..a0.67..CD13']
CD56..a0.67..CD117 = Data[,'CD56..a0.67..CD117']
CD45..a0.67..CD34 = Data[,'CD45..a0.67..CD34']
CD45..a0.67..CD33 = Data[,'CD45..a0.67..CD33']
CD45..a0.67..CD13 = Data[,'CD45..a0.67..CD13']
CD45..a0.67..CD117 = Data[,'CD45..a0.67..CD117']
CD34..a0.67..CD33 = Data[,'CD34..a0.67..CD33']
CD34..a0.67..CD13 = Data[,'CD34..a0.67..CD13']
CD34..a0.67..CD117 = Data[,'CD34..a0.67..CD117']
CD33..a0.67..CD13 = Data[,'CD33..a0.67..CD13']
CD33..a0.67..CD117 = Data[,'CD33..a0.67..CD117']
CD13..a0.67..CD117 = Data[,'CD13..a0.67..CD117']
SS..a0.75..FS = Data[,'SS..a0.75..FS']
SS..a0.75..HLA_DR = Data[,'SS..a0.75..HLA_DR']
SS..a0.75..CD7 = Data[,'SS..a0.75..CD7']
SS..a0.75..CD56 = Data[,'SS..a0.75..CD56']
SS..a0.75..CD45 = Data[,'SS..a0.75..CD45']
SS..a0.75..CD34 = Data[,'SS..a0.75..CD34']
SS..a0.75..CD33 = Data[,'SS..a0.75..CD33']
SS..a0.75..CD13 = Data[,'SS..a0.75..CD13']
SS..a0.75..CD117 = Data[,'SS..a0.75..CD117']
FS..a0.75..HLA_DR = Data[,'FS..a0.75..HLA_DR']
FS..a0.75..CD7 = Data[,'FS..a0.75..CD7']
FS..a0.75..CD56 = Data[,'FS..a0.75..CD56']
FS..a0.75..CD45 = Data[,'FS..a0.75..CD45']
FS..a0.75..CD34 = Data[,'FS..a0.75..CD34']
FS..a0.75..CD33 = Data[,'FS..a0.75..CD33']
FS..a0.75..CD13 = Data[,'FS..a0.75..CD13']
FS..a0.75..CD117 = Data[,'FS..a0.75..CD117']
HLA_DR..a0.75..CD7 = Data[,'HLA_DR..a0.75..CD7']
HLA_DR..a0.75..CD56 = Data[,'HLA_DR..a0.75..CD56']
HLA_DR..a0.75..CD45 = Data[,'HLA_DR..a0.75..CD45']
HLA_DR..a0.75..CD34 = Data[,'HLA_DR..a0.75..CD34']
HLA_DR..a0.75..CD33 = Data[,'HLA_DR..a0.75..CD33']
HLA_DR..a0.75..CD13 = Data[,'HLA_DR..a0.75..CD13']
HLA_DR..a0.75..CD117 = Data[,'HLA_DR..a0.75..CD117']
CD7..a0.75..CD56 = Data[,'CD7..a0.75..CD56']
CD7..a0.75..CD45 = Data[,'CD7..a0.75..CD45']
CD7..a0.75..CD34 = Data[,'CD7..a0.75..CD34']
CD7..a0.75..CD33 = Data[,'CD7..a0.75..CD33']
CD7..a0.75..CD13 = Data[,'CD7..a0.75..CD13']
CD7..a0.75..CD117 = Data[,'CD7..a0.75..CD117']
CD56..a0.75..CD45 = Data[,'CD56..a0.75..CD45']
CD56..a0.75..CD34 = Data[,'CD56..a0.75..CD34']
CD56..a0.75..CD33 = Data[,'CD56..a0.75..CD33']
CD56..a0.75..CD13 = Data[,'CD56..a0.75..CD13']
CD56..a0.75..CD117 = Data[,'CD56..a0.75..CD117']
CD45..a0.75..CD34 = Data[,'CD45..a0.75..CD34']
CD45..a0.75..CD33 = Data[,'CD45..a0.75..CD33']
CD45..a0.75..CD13 = Data[,'CD45..a0.75..CD13']
CD45..a0.75..CD117 = Data[,'CD45..a0.75..CD117']
CD34..a0.75..CD33 = Data[,'CD34..a0.75..CD33']
CD34..a0.75..CD13 = Data[,'CD34..a0.75..CD13']
CD34..a0.75..CD117 = Data[,'CD34..a0.75..CD117']
CD33..a0.75..CD13 = Data[,'CD33..a0.75..CD13']
CD33..a0.75..CD117 = Data[,'CD33..a0.75..CD117']
CD13..a0.75..CD117 = Data[,'CD13..a0.75..CD117']
SS..n0.25..FS = Data[,'SS..n0.25..FS']
SS..n0.25..HLA_DR = Data[,'SS..n0.25..HLA_DR']
SS..n0.25..CD7 = Data[,'SS..n0.25..CD7']
SS..n0.25..CD56 = Data[,'SS..n0.25..CD56']
SS..n0.25..CD45 = Data[,'SS..n0.25..CD45']
SS..n0.25..CD34 = Data[,'SS..n0.25..CD34']
SS..n0.25..CD33 = Data[,'SS..n0.25..CD33']
SS..n0.25..CD13 = Data[,'SS..n0.25..CD13']
SS..n0.25..CD117 = Data[,'SS..n0.25..CD117']
FS..n0.25..HLA_DR = Data[,'FS..n0.25..HLA_DR']
FS..n0.25..CD7 = Data[,'FS..n0.25..CD7']
FS..n0.25..CD56 = Data[,'FS..n0.25..CD56']
FS..n0.25..CD45 = Data[,'FS..n0.25..CD45']
FS..n0.25..CD34 = Data[,'FS..n0.25..CD34']
FS..n0.25..CD33 = Data[,'FS..n0.25..CD33']
FS..n0.25..CD13 = Data[,'FS..n0.25..CD13']
FS..n0.25..CD117 = Data[,'FS..n0.25..CD117']
HLA_DR..n0.25..CD7 = Data[,'HLA_DR..n0.25..CD7']
HLA_DR..n0.25..CD56 = Data[,'HLA_DR..n0.25..CD56']
HLA_DR..n0.25..CD45 = Data[,'HLA_DR..n0.25..CD45']
HLA_DR..n0.25..CD34 = Data[,'HLA_DR..n0.25..CD34']
HLA_DR..n0.25..CD33 = Data[,'HLA_DR..n0.25..CD33']
HLA_DR..n0.25..CD13 = Data[,'HLA_DR..n0.25..CD13']
HLA_DR..n0.25..CD117 = Data[,'HLA_DR..n0.25..CD117']
CD7..n0.25..CD56 = Data[,'CD7..n0.25..CD56']
CD7..n0.25..CD45 = Data[,'CD7..n0.25..CD45']
CD7..n0.25..CD34 = Data[,'CD7..n0.25..CD34']
CD7..n0.25..CD33 = Data[,'CD7..n0.25..CD33']
CD7..n0.25..CD13 = Data[,'CD7..n0.25..CD13']
CD7..n0.25..CD117 = Data[,'CD7..n0.25..CD117']
CD56..n0.25..CD45 = Data[,'CD56..n0.25..CD45']
CD56..n0.25..CD34 = Data[,'CD56..n0.25..CD34']
CD56..n0.25..CD33 = Data[,'CD56..n0.25..CD33']
CD56..n0.25..CD13 = Data[,'CD56..n0.25..CD13']
CD56..n0.25..CD117 = Data[,'CD56..n0.25..CD117']
CD45..n0.25..CD34 = Data[,'CD45..n0.25..CD34']
CD45..n0.25..CD33 = Data[,'CD45..n0.25..CD33']
CD45..n0.25..CD13 = Data[,'CD45..n0.25..CD13']
CD45..n0.25..CD117 = Data[,'CD45..n0.25..CD117']
CD34..n0.25..CD33 = Data[,'CD34..n0.25..CD33']
CD34..n0.25..CD13 = Data[,'CD34..n0.25..CD13']
CD34..n0.25..CD117 = Data[,'CD34..n0.25..CD117']
CD33..n0.25..CD13 = Data[,'CD33..n0.25..CD13']
CD33..n0.25..CD117 = Data[,'CD33..n0.25..CD117']
CD13..n0.25..CD117 = Data[,'CD13..n0.25..CD117']
SS..n0.33..FS = Data[,'SS..n0.33..FS']
SS..n0.33..HLA_DR = Data[,'SS..n0.33..HLA_DR']
SS..n0.33..CD7 = Data[,'SS..n0.33..CD7']
SS..n0.33..CD56 = Data[,'SS..n0.33..CD56']
SS..n0.33..CD45 = Data[,'SS..n0.33..CD45']
SS..n0.33..CD34 = Data[,'SS..n0.33..CD34']
SS..n0.33..CD33 = Data[,'SS..n0.33..CD33']
SS..n0.33..CD13 = Data[,'SS..n0.33..CD13']
SS..n0.33..CD117 = Data[,'SS..n0.33..CD117']
FS..n0.33..HLA_DR = Data[,'FS..n0.33..HLA_DR']
FS..n0.33..CD7 = Data[,'FS..n0.33..CD7']
FS..n0.33..CD56 = Data[,'FS..n0.33..CD56']
FS..n0.33..CD45 = Data[,'FS..n0.33..CD45']
FS..n0.33..CD34 = Data[,'FS..n0.33..CD34']
FS..n0.33..CD33 = Data[,'FS..n0.33..CD33']
FS..n0.33..CD13 = Data[,'FS..n0.33..CD13']
FS..n0.33..CD117 = Data[,'FS..n0.33..CD117']
HLA_DR..n0.33..CD7 = Data[,'HLA_DR..n0.33..CD7']
HLA_DR..n0.33..CD56 = Data[,'HLA_DR..n0.33..CD56']
HLA_DR..n0.33..CD45 = Data[,'HLA_DR..n0.33..CD45']
HLA_DR..n0.33..CD34 = Data[,'HLA_DR..n0.33..CD34']
HLA_DR..n0.33..CD33 = Data[,'HLA_DR..n0.33..CD33']
HLA_DR..n0.33..CD13 = Data[,'HLA_DR..n0.33..CD13']
HLA_DR..n0.33..CD117 = Data[,'HLA_DR..n0.33..CD117']
CD7..n0.33..CD56 = Data[,'CD7..n0.33..CD56']
CD7..n0.33..CD45 = Data[,'CD7..n0.33..CD45']
CD7..n0.33..CD34 = Data[,'CD7..n0.33..CD34']
CD7..n0.33..CD33 = Data[,'CD7..n0.33..CD33']
CD7..n0.33..CD13 = Data[,'CD7..n0.33..CD13']
CD7..n0.33..CD117 = Data[,'CD7..n0.33..CD117']
CD56..n0.33..CD45 = Data[,'CD56..n0.33..CD45']
CD56..n0.33..CD34 = Data[,'CD56..n0.33..CD34']
CD56..n0.33..CD33 = Data[,'CD56..n0.33..CD33']
CD56..n0.33..CD13 = Data[,'CD56..n0.33..CD13']
CD56..n0.33..CD117 = Data[,'CD56..n0.33..CD117']
CD45..n0.33..CD34 = Data[,'CD45..n0.33..CD34']
CD45..n0.33..CD33 = Data[,'CD45..n0.33..CD33']
CD45..n0.33..CD13 = Data[,'CD45..n0.33..CD13']
CD45..n0.33..CD117 = Data[,'CD45..n0.33..CD117']
CD34..n0.33..CD33 = Data[,'CD34..n0.33..CD33']
CD34..n0.33..CD13 = Data[,'CD34..n0.33..CD13']
CD34..n0.33..CD117 = Data[,'CD34..n0.33..CD117']
CD33..n0.33..CD13 = Data[,'CD33..n0.33..CD13']
CD33..n0.33..CD117 = Data[,'CD33..n0.33..CD117']
CD13..n0.33..CD117 = Data[,'CD13..n0.33..CD117']
SS..n0.5..FS = Data[,'SS..n0.5..FS']
SS..n0.5..HLA_DR = Data[,'SS..n0.5..HLA_DR']
SS..n0.5..CD7 = Data[,'SS..n0.5..CD7']
SS..n0.5..CD56 = Data[,'SS..n0.5..CD56']
SS..n0.5..CD45 = Data[,'SS..n0.5..CD45']
SS..n0.5..CD34 = Data[,'SS..n0.5..CD34']
SS..n0.5..CD33 = Data[,'SS..n0.5..CD33']
SS..n0.5..CD13 = Data[,'SS..n0.5..CD13']
SS..n0.5..CD117 = Data[,'SS..n0.5..CD117']
FS..n0.5..HLA_DR = Data[,'FS..n0.5..HLA_DR']
FS..n0.5..CD7 = Data[,'FS..n0.5..CD7']
FS..n0.5..CD56 = Data[,'FS..n0.5..CD56']
FS..n0.5..CD45 = Data[,'FS..n0.5..CD45']
FS..n0.5..CD34 = Data[,'FS..n0.5..CD34']
FS..n0.5..CD33 = Data[,'FS..n0.5..CD33']
FS..n0.5..CD13 = Data[,'FS..n0.5..CD13']
FS..n0.5..CD117 = Data[,'FS..n0.5..CD117']
HLA_DR..n0.5..CD7 = Data[,'HLA_DR..n0.5..CD7']
HLA_DR..n0.5..CD56 = Data[,'HLA_DR..n0.5..CD56']
HLA_DR..n0.5..CD45 = Data[,'HLA_DR..n0.5..CD45']
HLA_DR..n0.5..CD34 = Data[,'HLA_DR..n0.5..CD34']
HLA_DR..n0.5..CD33 = Data[,'HLA_DR..n0.5..CD33']
HLA_DR..n0.5..CD13 = Data[,'HLA_DR..n0.5..CD13']
HLA_DR..n0.5..CD117 = Data[,'HLA_DR..n0.5..CD117']
CD7..n0.5..CD56 = Data[,'CD7..n0.5..CD56']
CD7..n0.5..CD45 = Data[,'CD7..n0.5..CD45']
CD7..n0.5..CD34 = Data[,'CD7..n0.5..CD34']
CD7..n0.5..CD33 = Data[,'CD7..n0.5..CD33']
CD7..n0.5..CD13 = Data[,'CD7..n0.5..CD13']
CD7..n0.5..CD117 = Data[,'CD7..n0.5..CD117']
CD56..n0.5..CD45 = Data[,'CD56..n0.5..CD45']
CD56..n0.5..CD34 = Data[,'CD56..n0.5..CD34']
CD56..n0.5..CD33 = Data[,'CD56..n0.5..CD33']
CD56..n0.5..CD13 = Data[,'CD56..n0.5..CD13']
CD56..n0.5..CD117 = Data[,'CD56..n0.5..CD117']
CD45..n0.5..CD34 = Data[,'CD45..n0.5..CD34']
CD45..n0.5..CD33 = Data[,'CD45..n0.5..CD33']
CD45..n0.5..CD13 = Data[,'CD45..n0.5..CD13']
CD45..n0.5..CD117 = Data[,'CD45..n0.5..CD117']
CD34..n0.5..CD33 = Data[,'CD34..n0.5..CD33']
CD34..n0.5..CD13 = Data[,'CD34..n0.5..CD13']
CD34..n0.5..CD117 = Data[,'CD34..n0.5..CD117']
CD33..n0.5..CD13 = Data[,'CD33..n0.5..CD13']
CD33..n0.5..CD117 = Data[,'CD33..n0.5..CD117']
CD13..n0.5..CD117 = Data[,'CD13..n0.5..CD117']
SS..n0.67..FS = Data[,'SS..n0.67..FS']
SS..n0.67..HLA_DR = Data[,'SS..n0.67..HLA_DR']
SS..n0.67..CD7 = Data[,'SS..n0.67..CD7']
SS..n0.67..CD56 = Data[,'SS..n0.67..CD56']
SS..n0.67..CD45 = Data[,'SS..n0.67..CD45']
SS..n0.67..CD34 = Data[,'SS..n0.67..CD34']
SS..n0.67..CD33 = Data[,'SS..n0.67..CD33']
SS..n0.67..CD13 = Data[,'SS..n0.67..CD13']
SS..n0.67..CD117 = Data[,'SS..n0.67..CD117']
FS..n0.67..HLA_DR = Data[,'FS..n0.67..HLA_DR']
FS..n0.67..CD7 = Data[,'FS..n0.67..CD7']
FS..n0.67..CD56 = Data[,'FS..n0.67..CD56']
FS..n0.67..CD45 = Data[,'FS..n0.67..CD45']
FS..n0.67..CD34 = Data[,'FS..n0.67..CD34']
FS..n0.67..CD33 = Data[,'FS..n0.67..CD33']
FS..n0.67..CD13 = Data[,'FS..n0.67..CD13']
FS..n0.67..CD117 = Data[,'FS..n0.67..CD117']
HLA_DR..n0.67..CD7 = Data[,'HLA_DR..n0.67..CD7']
HLA_DR..n0.67..CD56 = Data[,'HLA_DR..n0.67..CD56']
HLA_DR..n0.67..CD45 = Data[,'HLA_DR..n0.67..CD45']
HLA_DR..n0.67..CD34 = Data[,'HLA_DR..n0.67..CD34']
HLA_DR..n0.67..CD33 = Data[,'HLA_DR..n0.67..CD33']
HLA_DR..n0.67..CD13 = Data[,'HLA_DR..n0.67..CD13']
HLA_DR..n0.67..CD117 = Data[,'HLA_DR..n0.67..CD117']
CD7..n0.67..CD56 = Data[,'CD7..n0.67..CD56']
CD7..n0.67..CD45 = Data[,'CD7..n0.67..CD45']
CD7..n0.67..CD34 = Data[,'CD7..n0.67..CD34']
CD7..n0.67..CD33 = Data[,'CD7..n0.67..CD33']
CD7..n0.67..CD13 = Data[,'CD7..n0.67..CD13']
CD7..n0.67..CD117 = Data[,'CD7..n0.67..CD117']
CD56..n0.67..CD45 = Data[,'CD56..n0.67..CD45']
CD56..n0.67..CD34 = Data[,'CD56..n0.67..CD34']
CD56..n0.67..CD33 = Data[,'CD56..n0.67..CD33']
CD56..n0.67..CD13 = Data[,'CD56..n0.67..CD13']
CD56..n0.67..CD117 = Data[,'CD56..n0.67..CD117']
CD45..n0.67..CD34 = Data[,'CD45..n0.67..CD34']
CD45..n0.67..CD33 = Data[,'CD45..n0.67..CD33']
CD45..n0.67..CD13 = Data[,'CD45..n0.67..CD13']
CD45..n0.67..CD117 = Data[,'CD45..n0.67..CD117']
CD34..n0.67..CD33 = Data[,'CD34..n0.67..CD33']
CD34..n0.67..CD13 = Data[,'CD34..n0.67..CD13']
CD34..n0.67..CD117 = Data[,'CD34..n0.67..CD117']
CD33..n0.67..CD13 = Data[,'CD33..n0.67..CD13']
CD33..n0.67..CD117 = Data[,'CD33..n0.67..CD117']
CD13..n0.67..CD117 = Data[,'CD13..n0.67..CD117']
SS..n0.75..FS = Data[,'SS..n0.75..FS']
SS..n0.75..HLA_DR = Data[,'SS..n0.75..HLA_DR']
SS..n0.75..CD7 = Data[,'SS..n0.75..CD7']
SS..n0.75..CD56 = Data[,'SS..n0.75..CD56']
SS..n0.75..CD45 = Data[,'SS..n0.75..CD45']
SS..n0.75..CD34 = Data[,'SS..n0.75..CD34']
SS..n0.75..CD33 = Data[,'SS..n0.75..CD33']
SS..n0.75..CD13 = Data[,'SS..n0.75..CD13']
SS..n0.75..CD117 = Data[,'SS..n0.75..CD117']
FS..n0.75..HLA_DR = Data[,'FS..n0.75..HLA_DR']
FS..n0.75..CD7 = Data[,'FS..n0.75..CD7']
FS..n0.75..CD56 = Data[,'FS..n0.75..CD56']
FS..n0.75..CD45 = Data[,'FS..n0.75..CD45']
FS..n0.75..CD34 = Data[,'FS..n0.75..CD34']
FS..n0.75..CD33 = Data[,'FS..n0.75..CD33']
FS..n0.75..CD13 = Data[,'FS..n0.75..CD13']
FS..n0.75..CD117 = Data[,'FS..n0.75..CD117']
HLA_DR..n0.75..CD7 = Data[,'HLA_DR..n0.75..CD7']
HLA_DR..n0.75..CD56 = Data[,'HLA_DR..n0.75..CD56']
HLA_DR..n0.75..CD45 = Data[,'HLA_DR..n0.75..CD45']
HLA_DR..n0.75..CD34 = Data[,'HLA_DR..n0.75..CD34']
HLA_DR..n0.75..CD33 = Data[,'HLA_DR..n0.75..CD33']
HLA_DR..n0.75..CD13 = Data[,'HLA_DR..n0.75..CD13']
HLA_DR..n0.75..CD117 = Data[,'HLA_DR..n0.75..CD117']
CD7..n0.75..CD56 = Data[,'CD7..n0.75..CD56']
CD7..n0.75..CD45 = Data[,'CD7..n0.75..CD45']
CD7..n0.75..CD34 = Data[,'CD7..n0.75..CD34']
CD7..n0.75..CD33 = Data[,'CD7..n0.75..CD33']
CD7..n0.75..CD13 = Data[,'CD7..n0.75..CD13']
CD7..n0.75..CD117 = Data[,'CD7..n0.75..CD117']
CD56..n0.75..CD45 = Data[,'CD56..n0.75..CD45']
CD56..n0.75..CD34 = Data[,'CD56..n0.75..CD34']
CD56..n0.75..CD33 = Data[,'CD56..n0.75..CD33']
CD56..n0.75..CD13 = Data[,'CD56..n0.75..CD13']
CD56..n0.75..CD117 = Data[,'CD56..n0.75..CD117']
CD45..n0.75..CD34 = Data[,'CD45..n0.75..CD34']
CD45..n0.75..CD33 = Data[,'CD45..n0.75..CD33']
CD45..n0.75..CD13 = Data[,'CD45..n0.75..CD13']
CD45..n0.75..CD117 = Data[,'CD45..n0.75..CD117']
CD34..n0.75..CD33 = Data[,'CD34..n0.75..CD33']
CD34..n0.75..CD13 = Data[,'CD34..n0.75..CD13']
CD34..n0.75..CD117 = Data[,'CD34..n0.75..CD117']
CD33..n0.75..CD13 = Data[,'CD33..n0.75..CD13']
CD33..n0.75..CD117 = Data[,'CD33..n0.75..CD117']
CD13..n0.75..CD117 = Data[,'CD13..n0.75..CD117']
 
Ind1 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR < 4.02875 & CD117 < 2.525 & CD33..a0.5..CD13 < 4.0575 & SS..n0.75..CD34 < 0.92625 & HLA_DR..a0.25..CD45 < 2.99625 & CD45..n0.75..CD34 < 1.65375 & SS..n0.75..CD45 < 0.27625 & CD34..a0.33..CD13 < 2.295)
Ind2 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR < 4.02875 & CD117 < 2.525 & CD33..a0.5..CD13 < 4.0575 & SS..n0.75..CD34 < 0.92625 & HLA_DR..a0.25..CD45 < 2.99625 & CD45..n0.75..CD34 < 1.65375 & SS..n0.75..CD45 < 0.27625 & CD34..a0.33..CD13 >= 2.295 & CD7..a0.75..CD13 < 4.35375 & CD45..n0.75..CD34 < 1.54375 & HLA_DR..a0.33..CD34 < 2.965 & SS..n0.75..CD45 < 0.0987499999999999 & CD117 < 2.355 & HLA_DR..a0.5..CD13 < 3.7375 & CD45..n0.67..CD34 < 1.55166666666667 & CD56..n0.67..CD45 < 1.39166666666667 & CD13 < 2.815 & HLA_DR..a0.5..CD7 < 0.89)
Ind3 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR < 4.02875 & CD117 < 2.525 & CD33..a0.5..CD13 < 4.0575 & SS..n0.75..CD34 < 0.92625 & HLA_DR..a0.25..CD45 < 2.99625 & CD45..n0.75..CD34 < 1.65375 & SS..n0.75..CD45 < 0.27625 & CD34..a0.33..CD13 >= 2.295 & CD7..a0.75..CD13 < 4.35375 & CD45..n0.75..CD34 < 1.54375 & HLA_DR..a0.33..CD34 < 2.965 & SS..n0.75..CD45 < 0.0987499999999999 & CD117 < 2.355 & HLA_DR..a0.5..CD13 < 3.7375 & CD45..n0.67..CD34 < 1.55166666666667 & CD56..n0.67..CD45 < 1.39166666666667 & CD13 < 2.815 & HLA_DR..a0.5..CD7 >= 0.89 & HLA_DR..a0.67..CD7 < 3.66833333333333 & CD34..n0.75..CD117 < 0.15875)
Ind4 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR < 4.02875 & CD117 < 2.525 & CD33..a0.5..CD13 < 4.0575 & SS..n0.75..CD34 < 0.92625 & HLA_DR..a0.25..CD45 < 2.99625 & CD45..n0.75..CD34 < 1.65375 & SS..n0.75..CD45 < 0.27625 & CD34..a0.33..CD13 >= 2.295 & CD7..a0.75..CD13 < 4.35375 & CD45..n0.75..CD34 < 1.54375 & HLA_DR..a0.33..CD34 < 2.965 & SS..n0.75..CD45 < 0.0987499999999999 & CD117 < 2.355 & HLA_DR..a0.5..CD13 < 3.7375 & CD45..n0.67..CD34 < 1.55166666666667 & CD56..n0.67..CD45 < 1.39166666666667 & CD13 < 2.815 & HLA_DR..a0.5..CD7 >= 0.89 & HLA_DR..a0.67..CD7 < 3.66833333333333 & CD34..n0.75..CD117 >= 0.15875 & CD33..a0.25..CD117 < 3.43875)
Ind5 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR < 4.02875 & CD117 < 2.525 & CD33..a0.5..CD13 < 4.0575 & SS..n0.75..CD34 < 0.92625 & HLA_DR..a0.25..CD45 < 2.99625 & CD45..n0.75..CD34 < 1.65375 & SS..n0.75..CD45 < 0.27625 & CD34..a0.33..CD13 >= 2.295 & CD7..a0.75..CD13 < 4.35375 & CD45..n0.75..CD34 < 1.54375 & HLA_DR..a0.33..CD34 < 2.965 & SS..n0.75..CD45 < 0.0987499999999999 & CD117 < 2.355 & HLA_DR..a0.5..CD13 < 3.7375 & CD45..n0.67..CD34 < 1.55166666666667 & CD56..n0.67..CD45 < 1.39166666666667 & CD13 < 2.815 & HLA_DR..a0.5..CD7 >= 0.89 & HLA_DR..a0.67..CD7 < 3.66833333333333 & CD34..n0.75..CD117 >= 0.15875 & CD33..a0.25..CD117 >= 3.43875)
Ind6 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR < 4.02875 & CD117 < 2.525 & CD33..a0.5..CD13 < 4.0575 & SS..n0.75..CD34 < 0.92625 & HLA_DR..a0.25..CD45 < 2.99625 & CD45..n0.75..CD34 < 1.65375 & SS..n0.75..CD45 < 0.27625 & CD34..a0.33..CD13 >= 2.295 & CD7..a0.75..CD13 < 4.35375 & CD45..n0.75..CD34 < 1.54375 & HLA_DR..a0.33..CD34 < 2.965 & SS..n0.75..CD45 < 0.0987499999999999 & CD117 < 2.355 & HLA_DR..a0.5..CD13 < 3.7375 & CD45..n0.67..CD34 < 1.55166666666667 & CD56..n0.67..CD45 < 1.39166666666667 & CD13 < 2.815 & HLA_DR..a0.5..CD7 >= 0.89 & HLA_DR..a0.67..CD7 >= 3.66833333333333)
Ind7 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR < 4.02875 & CD117 < 2.525 & CD33..a0.5..CD13 < 4.0575 & SS..n0.75..CD34 < 0.92625 & HLA_DR..a0.25..CD45 < 2.99625 & CD45..n0.75..CD34 < 1.65375 & SS..n0.75..CD45 < 0.27625 & CD34..a0.33..CD13 >= 2.295 & CD7..a0.75..CD13 < 4.35375 & CD45..n0.75..CD34 < 1.54375 & HLA_DR..a0.33..CD34 < 2.965 & SS..n0.75..CD45 < 0.0987499999999999 & CD117 < 2.355 & HLA_DR..a0.5..CD13 < 3.7375 & CD45..n0.67..CD34 < 1.55166666666667 & CD56..n0.67..CD45 < 1.39166666666667 & CD13 >= 2.815)
Ind8 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR < 4.02875 & CD117 < 2.525 & CD33..a0.5..CD13 < 4.0575 & SS..n0.75..CD34 < 0.92625 & HLA_DR..a0.25..CD45 < 2.99625 & CD45..n0.75..CD34 < 1.65375 & SS..n0.75..CD45 < 0.27625 & CD34..a0.33..CD13 >= 2.295 & CD7..a0.75..CD13 < 4.35375 & CD45..n0.75..CD34 < 1.54375 & HLA_DR..a0.33..CD34 < 2.965 & SS..n0.75..CD45 < 0.0987499999999999 & CD117 < 2.355 & HLA_DR..a0.5..CD13 < 3.7375 & CD45..n0.67..CD34 < 1.55166666666667 & CD56..n0.67..CD45 >= 1.39166666666667)
Ind9 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR < 4.02875 & CD117 < 2.525 & CD33..a0.5..CD13 < 4.0575 & SS..n0.75..CD34 < 0.92625 & HLA_DR..a0.25..CD45 < 2.99625 & CD45..n0.75..CD34 < 1.65375 & SS..n0.75..CD45 < 0.27625 & CD34..a0.33..CD13 >= 2.295 & CD7..a0.75..CD13 < 4.35375 & CD45..n0.75..CD34 < 1.54375 & HLA_DR..a0.33..CD34 < 2.965 & SS..n0.75..CD45 < 0.0987499999999999 & CD117 < 2.355 & HLA_DR..a0.5..CD13 < 3.7375 & CD45..n0.67..CD34 >= 1.55166666666667)
Ind10 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR < 4.02875 & CD117 < 2.525 & CD33..a0.5..CD13 < 4.0575 & SS..n0.75..CD34 < 0.92625 & HLA_DR..a0.25..CD45 < 2.99625 & CD45..n0.75..CD34 < 1.65375 & SS..n0.75..CD45 < 0.27625 & CD34..a0.33..CD13 >= 2.295 & CD7..a0.75..CD13 < 4.35375 & CD45..n0.75..CD34 < 1.54375 & HLA_DR..a0.33..CD34 < 2.965 & SS..n0.75..CD45 < 0.0987499999999999 & CD117 < 2.355 & HLA_DR..a0.5..CD13 >= 3.7375)
Ind11 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR < 4.02875 & CD117 < 2.525 & CD33..a0.5..CD13 < 4.0575 & SS..n0.75..CD34 < 0.92625 & HLA_DR..a0.25..CD45 < 2.99625 & CD45..n0.75..CD34 < 1.65375 & SS..n0.75..CD45 < 0.27625 & CD34..a0.33..CD13 >= 2.295 & CD7..a0.75..CD13 < 4.35375 & CD45..n0.75..CD34 < 1.54375 & HLA_DR..a0.33..CD34 < 2.965 & SS..n0.75..CD45 < 0.0987499999999999 & CD117 >= 2.355)
Ind12 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR < 4.02875 & CD117 < 2.525 & CD33..a0.5..CD13 < 4.0575 & SS..n0.75..CD34 < 0.92625 & HLA_DR..a0.25..CD45 < 2.99625 & CD45..n0.75..CD34 < 1.65375 & SS..n0.75..CD45 < 0.27625 & CD34..a0.33..CD13 >= 2.295 & CD7..a0.75..CD13 < 4.35375 & CD45..n0.75..CD34 < 1.54375 & HLA_DR..a0.33..CD34 < 2.965 & SS..n0.75..CD45 >= 0.0987499999999999)
Ind13 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR < 4.02875 & CD117 < 2.525 & CD33..a0.5..CD13 < 4.0575 & SS..n0.75..CD34 < 0.92625 & HLA_DR..a0.25..CD45 < 2.99625 & CD45..n0.75..CD34 < 1.65375 & SS..n0.75..CD45 < 0.27625 & CD34..a0.33..CD13 >= 2.295 & CD7..a0.75..CD13 < 4.35375 & CD45..n0.75..CD34 < 1.54375 & HLA_DR..a0.33..CD34 >= 2.965)
Ind14 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR < 4.02875 & CD117 < 2.525 & CD33..a0.5..CD13 < 4.0575 & SS..n0.75..CD34 < 0.92625 & HLA_DR..a0.25..CD45 < 2.99625 & CD45..n0.75..CD34 < 1.65375 & SS..n0.75..CD45 < 0.27625 & CD34..a0.33..CD13 >= 2.295 & CD7..a0.75..CD13 < 4.35375 & CD45..n0.75..CD34 >= 1.54375)
Ind15 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR < 4.02875 & CD117 < 2.525 & CD33..a0.5..CD13 < 4.0575 & SS..n0.75..CD34 < 0.92625 & HLA_DR..a0.25..CD45 < 2.99625 & CD45..n0.75..CD34 < 1.65375 & SS..n0.75..CD45 < 0.27625 & CD34..a0.33..CD13 >= 2.295 & CD7..a0.75..CD13 >= 4.35375)
Ind16 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR < 4.02875 & CD117 < 2.525 & CD33..a0.5..CD13 < 4.0575 & SS..n0.75..CD34 < 0.92625 & HLA_DR..a0.25..CD45 < 2.99625 & CD45..n0.75..CD34 < 1.65375 & SS..n0.75..CD45 >= 0.27625)
Ind17 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR < 4.02875 & CD117 < 2.525 & CD33..a0.5..CD13 < 4.0575 & SS..n0.75..CD34 < 0.92625 & HLA_DR..a0.25..CD45 < 2.99625 & CD45..n0.75..CD34 >= 1.65375)
Ind18 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR < 4.02875 & CD117 < 2.525 & CD33..a0.5..CD13 < 4.0575 & SS..n0.75..CD34 < 0.92625 & HLA_DR..a0.25..CD45 >= 2.99625)
Ind19 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR < 4.02875 & CD117 < 2.525 & CD33..a0.5..CD13 < 4.0575 & SS..n0.75..CD34 >= 0.92625)
Ind20 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR < 4.02875 & CD117 < 2.525 & CD33..a0.5..CD13 >= 4.0575)
Ind21 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR < 4.02875 & CD117 >= 2.525)
Ind22 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 < 2.0975 & HLA_DR..a0.75..CD7 < 3.91125 & CD33..a0.33..CD117 < 3.36833333333333 & CD7..a0.33..CD34 < 3.02833333333333 & FS..a0.67..CD7 < 5.525 & CD117 < 2.505)
Ind23 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 < 2.0975 & HLA_DR..a0.75..CD7 < 3.91125 & CD33..a0.33..CD117 < 3.36833333333333 & CD7..a0.33..CD34 < 3.02833333333333 & FS..a0.67..CD7 < 5.525 & CD117 >= 2.505)
Ind24 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 < 2.0975 & HLA_DR..a0.75..CD7 < 3.91125 & CD33..a0.33..CD117 < 3.36833333333333 & CD7..a0.33..CD34 < 3.02833333333333 & FS..a0.67..CD7 >= 5.525)
Ind25 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 < 2.0975 & HLA_DR..a0.75..CD7 < 3.91125 & CD33..a0.33..CD117 < 3.36833333333333 & CD7..a0.33..CD34 >= 3.02833333333333)
Ind26 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 < 2.0975 & HLA_DR..a0.75..CD7 < 3.91125 & CD33..a0.33..CD117 >= 3.36833333333333)
Ind27 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 < 2.0975 & HLA_DR..a0.75..CD7 >= 3.91125 & CD45..n0.5..CD33 < 1.9025 & CD33..a0.5..CD117 < 3.6475)
Ind28 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 < 2.0975 & HLA_DR..a0.75..CD7 >= 3.91125 & CD45..n0.5..CD33 < 1.9025 & CD33..a0.5..CD117 >= 3.6475 & CD34..n0.25..CD117 < 3.19125 & CD45..n0.33..CD33 < 2.55833333333333 & CD45..n0.33..CD34 < 1.68166666666667)
Ind29 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 < 2.0975 & HLA_DR..a0.75..CD7 >= 3.91125 & CD45..n0.5..CD33 < 1.9025 & CD33..a0.5..CD117 >= 3.6475 & CD34..n0.25..CD117 < 3.19125 & CD45..n0.33..CD33 < 2.55833333333333 & CD45..n0.33..CD34 >= 1.68166666666667 & CD45..n0.75..CD33 < 0.96375 & CD7..n0.67..CD34 < 1.68833333333333)
Ind30 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 < 2.0975 & HLA_DR..a0.75..CD7 >= 3.91125 & CD45..n0.5..CD33 < 1.9025 & CD33..a0.5..CD117 >= 3.6475 & CD34..n0.25..CD117 < 3.19125 & CD45..n0.33..CD33 < 2.55833333333333 & CD45..n0.33..CD34 >= 1.68166666666667 & CD45..n0.75..CD33 < 0.96375 & CD7..n0.67..CD34 >= 1.68833333333333)
Ind31 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 < 2.0975 & HLA_DR..a0.75..CD7 >= 3.91125 & CD45..n0.5..CD33 < 1.9025 & CD33..a0.5..CD117 >= 3.6475 & CD34..n0.25..CD117 < 3.19125 & CD45..n0.33..CD33 < 2.55833333333333 & CD45..n0.33..CD34 >= 1.68166666666667 & CD45..n0.75..CD33 >= 0.96375)
Ind32 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 < 2.0975 & HLA_DR..a0.75..CD7 >= 3.91125 & CD45..n0.5..CD33 < 1.9025 & CD33..a0.5..CD117 >= 3.6475 & CD34..n0.25..CD117 < 3.19125 & CD45..n0.33..CD33 >= 2.55833333333333)
Ind33 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 < 2.0975 & HLA_DR..a0.75..CD7 >= 3.91125 & CD45..n0.5..CD33 < 1.9025 & CD33..a0.5..CD117 >= 3.6475 & CD34..n0.25..CD117 >= 3.19125)
Ind34 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 < 2.0975 & HLA_DR..a0.75..CD7 >= 3.91125 & CD45..n0.5..CD33 >= 1.9025 & CD34..n0.33..CD33 < 1.72166666666667 & FS..n0.75..CD34 < 2.71625 & CD34..n0.75..CD13 < -0.60875)
Ind35 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 < 2.0975 & HLA_DR..a0.75..CD7 >= 3.91125 & CD45..n0.5..CD33 >= 1.9025 & CD34..n0.33..CD33 < 1.72166666666667 & FS..n0.75..CD34 < 2.71625 & CD34..n0.75..CD13 >= -0.60875 & HLA_DR..n0.75..CD33 < 1.35375)
Ind36 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 < 2.0975 & HLA_DR..a0.75..CD7 >= 3.91125 & CD45..n0.5..CD33 >= 1.9025 & CD34..n0.33..CD33 < 1.72166666666667 & FS..n0.75..CD34 < 2.71625 & CD34..n0.75..CD13 >= -0.60875 & HLA_DR..n0.75..CD33 >= 1.35375)
Ind37 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 < 2.0975 & HLA_DR..a0.75..CD7 >= 3.91125 & CD45..n0.5..CD33 >= 1.9025 & CD34..n0.33..CD33 < 1.72166666666667 & FS..n0.75..CD34 >= 2.71625)
Ind38 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 < 2.0975 & HLA_DR..a0.75..CD7 >= 3.91125 & CD45..n0.5..CD33 >= 1.9025 & CD34..n0.33..CD33 >= 1.72166666666667)
Ind39 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 >= 2.0975 & HLA_DR..n0.67..CD45 < 0.205 & HLA_DR..n0.75..CD34 < 0.66125 & FS..n0.75..CD7 < 0.73125)
Ind40 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 >= 2.0975 & HLA_DR..n0.67..CD45 < 0.205 & HLA_DR..n0.75..CD34 < 0.66125 & FS..n0.75..CD7 >= 0.73125 & CD56..a0.75..CD34 < 4.36875)
Ind41 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 >= 2.0975 & HLA_DR..n0.67..CD45 < 0.205 & HLA_DR..n0.75..CD34 < 0.66125 & FS..n0.75..CD7 >= 0.73125 & CD56..a0.75..CD34 >= 4.36875 & CD45..n0.75..CD117 < 1.57875)
Ind42 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 >= 2.0975 & HLA_DR..n0.67..CD45 < 0.205 & HLA_DR..n0.75..CD34 < 0.66125 & FS..n0.75..CD7 >= 0.73125 & CD56..a0.75..CD34 >= 4.36875 & CD45..n0.75..CD117 >= 1.57875)
Ind43 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 >= 2.0975 & HLA_DR..n0.67..CD45 < 0.205 & HLA_DR..n0.75..CD34 >= 0.66125 & CD34..n0.25..CD33 < 1.60875)
Ind44 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 >= 2.0975 & HLA_DR..n0.67..CD45 < 0.205 & HLA_DR..n0.75..CD34 >= 0.66125 & CD34..n0.25..CD33 >= 1.60875 & CD45..n0.67..CD33 < 1.64833333333333)
Ind45 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 >= 2.0975 & HLA_DR..n0.67..CD45 < 0.205 & HLA_DR..n0.75..CD34 >= 0.66125 & CD34..n0.25..CD33 >= 1.60875 & CD45..n0.67..CD33 >= 1.64833333333333 & CD7..n0.33..CD56 < 2.80833333333333 & CD45..n0.75..CD34 < 2.78125 & CD45..n0.25..CD33 < 3.18375)
Ind46 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 >= 2.0975 & HLA_DR..n0.67..CD45 < 0.205 & HLA_DR..n0.75..CD34 >= 0.66125 & CD34..n0.25..CD33 >= 1.60875 & CD45..n0.67..CD33 >= 1.64833333333333 & CD7..n0.33..CD56 < 2.80833333333333 & CD45..n0.75..CD34 < 2.78125 & CD45..n0.25..CD33 >= 3.18375 & SS..a0.75..FS < 5.46375)
Ind47 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 >= 2.0975 & HLA_DR..n0.67..CD45 < 0.205 & HLA_DR..n0.75..CD34 >= 0.66125 & CD34..n0.25..CD33 >= 1.60875 & CD45..n0.67..CD33 >= 1.64833333333333 & CD7..n0.33..CD56 < 2.80833333333333 & CD45..n0.75..CD34 < 2.78125 & CD45..n0.25..CD33 >= 3.18375 & SS..a0.75..FS >= 5.46375 & CD34..n0.75..CD13 < -0.7525)
Ind48 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 >= 2.0975 & HLA_DR..n0.67..CD45 < 0.205 & HLA_DR..n0.75..CD34 >= 0.66125 & CD34..n0.25..CD33 >= 1.60875 & CD45..n0.67..CD33 >= 1.64833333333333 & CD7..n0.33..CD56 < 2.80833333333333 & CD45..n0.75..CD34 < 2.78125 & CD45..n0.25..CD33 >= 3.18375 & SS..a0.75..FS >= 5.46375 & CD34..n0.75..CD13 >= -0.7525 & CD45..n0.67..CD34 < 2.82833333333333 & SS..n0.67..CD13 < 1.94166666666667 & CD56..n0.75..CD13 < 2.07125 & CD45..n0.5..CD117 < 2.6225)
Ind49 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 >= 2.0975 & HLA_DR..n0.67..CD45 < 0.205 & HLA_DR..n0.75..CD34 >= 0.66125 & CD34..n0.25..CD33 >= 1.60875 & CD45..n0.67..CD33 >= 1.64833333333333 & CD7..n0.33..CD56 < 2.80833333333333 & CD45..n0.75..CD34 < 2.78125 & CD45..n0.25..CD33 >= 3.18375 & SS..a0.75..FS >= 5.46375 & CD34..n0.75..CD13 >= -0.7525 & CD45..n0.67..CD34 < 2.82833333333333 & SS..n0.67..CD13 < 1.94166666666667 & CD56..n0.75..CD13 < 2.07125 & CD45..n0.5..CD117 >= 2.6225)
Ind50 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 >= 2.0975 & HLA_DR..n0.67..CD45 < 0.205 & HLA_DR..n0.75..CD34 >= 0.66125 & CD34..n0.25..CD33 >= 1.60875 & CD45..n0.67..CD33 >= 1.64833333333333 & CD7..n0.33..CD56 < 2.80833333333333 & CD45..n0.75..CD34 < 2.78125 & CD45..n0.25..CD33 >= 3.18375 & SS..a0.75..FS >= 5.46375 & CD34..n0.75..CD13 >= -0.7525 & CD45..n0.67..CD34 < 2.82833333333333 & SS..n0.67..CD13 < 1.94166666666667 & CD56..n0.75..CD13 >= 2.07125)
Ind51 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 >= 2.0975 & HLA_DR..n0.67..CD45 < 0.205 & HLA_DR..n0.75..CD34 >= 0.66125 & CD34..n0.25..CD33 >= 1.60875 & CD45..n0.67..CD33 >= 1.64833333333333 & CD7..n0.33..CD56 < 2.80833333333333 & CD45..n0.75..CD34 < 2.78125 & CD45..n0.25..CD33 >= 3.18375 & SS..a0.75..FS >= 5.46375 & CD34..n0.75..CD13 >= -0.7525 & CD45..n0.67..CD34 < 2.82833333333333 & SS..n0.67..CD13 >= 1.94166666666667)
Ind52 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 >= 2.0975 & HLA_DR..n0.67..CD45 < 0.205 & HLA_DR..n0.75..CD34 >= 0.66125 & CD34..n0.25..CD33 >= 1.60875 & CD45..n0.67..CD33 >= 1.64833333333333 & CD7..n0.33..CD56 < 2.80833333333333 & CD45..n0.75..CD34 < 2.78125 & CD45..n0.25..CD33 >= 3.18375 & SS..a0.75..FS >= 5.46375 & CD34..n0.75..CD13 >= -0.7525 & CD45..n0.67..CD34 >= 2.82833333333333)
Ind53 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 >= 2.0975 & HLA_DR..n0.67..CD45 < 0.205 & HLA_DR..n0.75..CD34 >= 0.66125 & CD34..n0.25..CD33 >= 1.60875 & CD45..n0.67..CD33 >= 1.64833333333333 & CD7..n0.33..CD56 < 2.80833333333333 & CD45..n0.75..CD34 >= 2.78125)
Ind54 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 >= 2.0975 & HLA_DR..n0.67..CD45 < 0.205 & HLA_DR..n0.75..CD34 >= 0.66125 & CD34..n0.25..CD33 >= 1.60875 & CD45..n0.67..CD33 >= 1.64833333333333 & CD7..n0.33..CD56 >= 2.80833333333333)
Ind55 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 >= 2.0975 & HLA_DR..n0.67..CD45 >= 0.205 & CD45..a0.33..CD13 < 4.835)
Ind56 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 >= 2.0975 & HLA_DR..n0.67..CD45 >= 0.205 & CD45..a0.33..CD13 >= 4.835 & CD45..n0.75..CD34 < 1.62625)
Ind57 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 >= 2.0975 & HLA_DR..n0.67..CD45 >= 0.205 & CD45..a0.33..CD13 >= 4.835 & CD45..n0.75..CD34 >= 1.62625 & CD34..n0.25..CD33 < 1.55375)
Ind58 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 >= 2.0975 & HLA_DR..n0.67..CD45 >= 0.205 & CD45..a0.33..CD13 >= 4.835 & CD45..n0.75..CD34 >= 1.62625 & CD34..n0.25..CD33 >= 1.55375 & CD34..n0.75..CD13 < -0.635)
Ind59 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 >= 2.0975 & HLA_DR..n0.67..CD45 >= 0.205 & CD45..a0.33..CD13 >= 4.835 & CD45..n0.75..CD34 >= 1.62625 & CD34..n0.25..CD33 >= 1.55375 & CD34..n0.75..CD13 >= -0.635 & CD45..n0.75..CD34 < 2.85625 & CD117 < 2.665 & FS..n0.75..CD56 < 2.72875 & CD34..n0.25..CD33 < 1.68625)
Ind60 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 >= 2.0975 & HLA_DR..n0.67..CD45 >= 0.205 & CD45..a0.33..CD13 >= 4.835 & CD45..n0.75..CD34 >= 1.62625 & CD34..n0.25..CD33 >= 1.55375 & CD34..n0.75..CD13 >= -0.635 & CD45..n0.75..CD34 < 2.85625 & CD117 < 2.665 & FS..n0.75..CD56 < 2.72875 & CD34..n0.25..CD33 >= 1.68625 & CD45..a0.33..CD13 < 5.115)
Ind61 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 >= 2.0975 & HLA_DR..n0.67..CD45 >= 0.205 & CD45..a0.33..CD13 >= 4.835 & CD45..n0.75..CD34 >= 1.62625 & CD34..n0.25..CD33 >= 1.55375 & CD34..n0.75..CD13 >= -0.635 & CD45..n0.75..CD34 < 2.85625 & CD117 < 2.665 & FS..n0.75..CD56 < 2.72875 & CD34..n0.25..CD33 >= 1.68625 & CD45..a0.33..CD13 >= 5.115 & CD56..a0.67..CD33 < 6.365 & CD33..n0.75..CD13 < 1.23375 & CD45..a0.33..CD33 < 5.99833333333333)
Ind62 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 >= 2.0975 & HLA_DR..n0.67..CD45 >= 0.205 & CD45..a0.33..CD13 >= 4.835 & CD45..n0.75..CD34 >= 1.62625 & CD34..n0.25..CD33 >= 1.55375 & CD34..n0.75..CD13 >= -0.635 & CD45..n0.75..CD34 < 2.85625 & CD117 < 2.665 & FS..n0.75..CD56 < 2.72875 & CD34..n0.25..CD33 >= 1.68625 & CD45..a0.33..CD13 >= 5.115 & CD56..a0.67..CD33 < 6.365 & CD33..n0.75..CD13 < 1.23375 & CD45..a0.33..CD33 >= 5.99833333333333)
Ind63 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 >= 2.0975 & HLA_DR..n0.67..CD45 >= 0.205 & CD45..a0.33..CD13 >= 4.835 & CD45..n0.75..CD34 >= 1.62625 & CD34..n0.25..CD33 >= 1.55375 & CD34..n0.75..CD13 >= -0.635 & CD45..n0.75..CD34 < 2.85625 & CD117 < 2.665 & FS..n0.75..CD56 < 2.72875 & CD34..n0.25..CD33 >= 1.68625 & CD45..a0.33..CD13 >= 5.115 & CD56..a0.67..CD33 < 6.365 & CD33..n0.75..CD13 >= 1.23375)
Ind64 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 >= 2.0975 & HLA_DR..n0.67..CD45 >= 0.205 & CD45..a0.33..CD13 >= 4.835 & CD45..n0.75..CD34 >= 1.62625 & CD34..n0.25..CD33 >= 1.55375 & CD34..n0.75..CD13 >= -0.635 & CD45..n0.75..CD34 < 2.85625 & CD117 < 2.665 & FS..n0.75..CD56 < 2.72875 & CD34..n0.25..CD33 >= 1.68625 & CD45..a0.33..CD13 >= 5.115 & CD56..a0.67..CD33 >= 6.365)
Ind65 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 >= 2.0975 & HLA_DR..n0.67..CD45 >= 0.205 & CD45..a0.33..CD13 >= 4.835 & CD45..n0.75..CD34 >= 1.62625 & CD34..n0.25..CD33 >= 1.55375 & CD34..n0.75..CD13 >= -0.635 & CD45..n0.75..CD34 < 2.85625 & CD117 < 2.665 & FS..n0.75..CD56 >= 2.72875 & SS..a0.67..CD7 < 6.43833333333333)
Ind66 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 >= 2.0975 & HLA_DR..n0.67..CD45 >= 0.205 & CD45..a0.33..CD13 >= 4.835 & CD45..n0.75..CD34 >= 1.62625 & CD34..n0.25..CD33 >= 1.55375 & CD34..n0.75..CD13 >= -0.635 & CD45..n0.75..CD34 < 2.85625 & CD117 < 2.665 & FS..n0.75..CD56 >= 2.72875 & SS..a0.67..CD7 >= 6.43833333333333)
Ind67 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 >= 2.0975 & HLA_DR..n0.67..CD45 >= 0.205 & CD45..a0.33..CD13 >= 4.835 & CD45..n0.75..CD34 >= 1.62625 & CD34..n0.25..CD33 >= 1.55375 & CD34..n0.75..CD13 >= -0.635 & CD45..n0.75..CD34 < 2.85625 & CD117 >= 2.665)
Ind68 = which(SS..n0.75..CD13 < 1.85625 & SS..a0.75..HLA_DR >= 4.02875 & CD45..n0.5..CD33 >= 2.0975 & HLA_DR..n0.67..CD45 >= 0.205 & CD45..a0.33..CD13 >= 4.835 & CD45..n0.75..CD34 >= 1.62625 & CD34..n0.25..CD33 >= 1.55375 & CD34..n0.75..CD13 >= -0.635 & CD45..n0.75..CD34 >= 2.85625)
Ind69 = which(SS..n0.75..CD13 >= 1.85625 & CD33..n0.33..CD13 < 2.20166666666667 & FS..n0.75..HLA_DR < 2.42375 & CD7..a0.75..CD45 < 3.84125)
Ind70 = which(SS..n0.75..CD13 >= 1.85625 & CD33..n0.33..CD13 < 2.20166666666667 & FS..n0.75..HLA_DR < 2.42375 & CD7..a0.75..CD45 >= 3.84125)
Ind71 = which(SS..n0.75..CD13 >= 1.85625 & CD33..n0.33..CD13 < 2.20166666666667 & FS..n0.75..HLA_DR >= 2.42375)
Ind72 = which(SS..n0.75..CD13 >= 1.85625 & CD33..n0.33..CD13 >= 2.20166666666667 & SS..n0.75..CD117 < 2.02125)
Ind73 = which(SS..n0.75..CD13 >= 1.85625 & CD33..n0.33..CD13 >= 2.20166666666667 & SS..n0.75..CD117 >= 2.02125 & CD45..n0.25..CD33 < 3.19875 & CD33..n0.67..CD13 < 1.11166666666667)
Ind74 = which(SS..n0.75..CD13 >= 1.85625 & CD33..n0.33..CD13 >= 2.20166666666667 & SS..n0.75..CD117 >= 2.02125 & CD45..n0.25..CD33 < 3.19875 & CD33..n0.67..CD13 >= 1.11166666666667 & CD33..a0.33..CD13 < 3.49)
Ind75 = which(SS..n0.75..CD13 >= 1.85625 & CD33..n0.33..CD13 >= 2.20166666666667 & SS..n0.75..CD117 >= 2.02125 & CD45..n0.25..CD33 < 3.19875 & CD33..n0.67..CD13 >= 1.11166666666667 & CD33..a0.33..CD13 >= 3.49 & FS..n0.75..CD34 < 2.60375 & CD45..n0.25..CD13 < 3.455 & CD7..n0.67..CD45 < 1.25333333333333)
Ind76 = which(SS..n0.75..CD13 >= 1.85625 & CD33..n0.33..CD13 >= 2.20166666666667 & SS..n0.75..CD117 >= 2.02125 & CD45..n0.25..CD33 < 3.19875 & CD33..n0.67..CD13 >= 1.11166666666667 & CD33..a0.33..CD13 >= 3.49 & FS..n0.75..CD34 < 2.60375 & CD45..n0.25..CD13 < 3.455 & CD7..n0.67..CD45 >= 1.25333333333333)
Ind77 = which(SS..n0.75..CD13 >= 1.85625 & CD33..n0.33..CD13 >= 2.20166666666667 & SS..n0.75..CD117 >= 2.02125 & CD45..n0.25..CD33 < 3.19875 & CD33..n0.67..CD13 >= 1.11166666666667 & CD33..a0.33..CD13 >= 3.49 & FS..n0.75..CD34 < 2.60375 & CD45..n0.25..CD13 >= 3.455)
Ind78 = which(SS..n0.75..CD13 >= 1.85625 & CD33..n0.33..CD13 >= 2.20166666666667 & SS..n0.75..CD117 >= 2.02125 & CD45..n0.25..CD33 < 3.19875 & CD33..n0.67..CD13 >= 1.11166666666667 & CD33..a0.33..CD13 >= 3.49 & FS..n0.75..CD34 >= 2.60375 & CD34..n0.5..CD33 < 0.7925 & FS..n0.25..CD7 < 3.44125)
Ind79 = which(SS..n0.75..CD13 >= 1.85625 & CD33..n0.33..CD13 >= 2.20166666666667 & SS..n0.75..CD117 >= 2.02125 & CD45..n0.25..CD33 < 3.19875 & CD33..n0.67..CD13 >= 1.11166666666667 & CD33..a0.33..CD13 >= 3.49 & FS..n0.75..CD34 >= 2.60375 & CD34..n0.5..CD33 < 0.7925 & FS..n0.25..CD7 >= 3.44125 & CD45 < 4.235 & CD45..n0.67..CD33 < -1.005)
Ind80 = which(SS..n0.75..CD13 >= 1.85625 & CD33..n0.33..CD13 >= 2.20166666666667 & SS..n0.75..CD117 >= 2.02125 & CD45..n0.25..CD33 < 3.19875 & CD33..n0.67..CD13 >= 1.11166666666667 & CD33..a0.33..CD13 >= 3.49 & FS..n0.75..CD34 >= 2.60375 & CD34..n0.5..CD33 < 0.7925 & FS..n0.25..CD7 >= 3.44125 & CD45 < 4.235 & CD45..n0.67..CD33 >= -1.005 & FS..n0.25..CD117 < 3.5625)
Ind81 = which(SS..n0.75..CD13 >= 1.85625 & CD33..n0.33..CD13 >= 2.20166666666667 & SS..n0.75..CD117 >= 2.02125 & CD45..n0.25..CD33 < 3.19875 & CD33..n0.67..CD13 >= 1.11166666666667 & CD33..a0.33..CD13 >= 3.49 & FS..n0.75..CD34 >= 2.60375 & CD34..n0.5..CD33 < 0.7925 & FS..n0.25..CD7 >= 3.44125 & CD45 < 4.235 & CD45..n0.67..CD33 >= -1.005 & FS..n0.25..CD117 >= 3.5625 & CD34..n0.5..CD33 < 0.7275 & CD34 < 0.63)
Ind82 = which(SS..n0.75..CD13 >= 1.85625 & CD33..n0.33..CD13 >= 2.20166666666667 & SS..n0.75..CD117 >= 2.02125 & CD45..n0.25..CD33 < 3.19875 & CD33..n0.67..CD13 >= 1.11166666666667 & CD33..a0.33..CD13 >= 3.49 & FS..n0.75..CD34 >= 2.60375 & CD34..n0.5..CD33 < 0.7925 & FS..n0.25..CD7 >= 3.44125 & CD45 < 4.235 & CD45..n0.67..CD33 >= -1.005 & FS..n0.25..CD117 >= 3.5625 & CD34..n0.5..CD33 < 0.7275 & CD34 >= 0.63 & FS..n0.25..HLA_DR < 4.58125 & SS..n0.25..CD56 < 2.93875)
Ind83 = which(SS..n0.75..CD13 >= 1.85625 & CD33..n0.33..CD13 >= 2.20166666666667 & SS..n0.75..CD117 >= 2.02125 & CD45..n0.25..CD33 < 3.19875 & CD33..n0.67..CD13 >= 1.11166666666667 & CD33..a0.33..CD13 >= 3.49 & FS..n0.75..CD34 >= 2.60375 & CD34..n0.5..CD33 < 0.7925 & FS..n0.25..CD7 >= 3.44125 & CD45 < 4.235 & CD45..n0.67..CD33 >= -1.005 & FS..n0.25..CD117 >= 3.5625 & CD34..n0.5..CD33 < 0.7275 & CD34 >= 0.63 & FS..n0.25..HLA_DR < 4.58125 & SS..n0.25..CD56 >= 2.93875 & SS..a0.25..CD34 < 4.095)
Ind84 = which(SS..n0.75..CD13 >= 1.85625 & CD33..n0.33..CD13 >= 2.20166666666667 & SS..n0.75..CD117 >= 2.02125 & CD45..n0.25..CD33 < 3.19875 & CD33..n0.67..CD13 >= 1.11166666666667 & CD33..a0.33..CD13 >= 3.49 & FS..n0.75..CD34 >= 2.60375 & CD34..n0.5..CD33 < 0.7925 & FS..n0.25..CD7 >= 3.44125 & CD45 < 4.235 & CD45..n0.67..CD33 >= -1.005 & FS..n0.25..CD117 >= 3.5625 & CD34..n0.5..CD33 < 0.7275 & CD34 >= 0.63 & FS..n0.25..HLA_DR < 4.58125 & SS..n0.25..CD56 >= 2.93875 & SS..a0.25..CD34 >= 4.095)
Ind85 = which(SS..n0.75..CD13 >= 1.85625 & CD33..n0.33..CD13 >= 2.20166666666667 & SS..n0.75..CD117 >= 2.02125 & CD45..n0.25..CD33 < 3.19875 & CD33..n0.67..CD13 >= 1.11166666666667 & CD33..a0.33..CD13 >= 3.49 & FS..n0.75..CD34 >= 2.60375 & CD34..n0.5..CD33 < 0.7925 & FS..n0.25..CD7 >= 3.44125 & CD45 < 4.235 & CD45..n0.67..CD33 >= -1.005 & FS..n0.25..CD117 >= 3.5625 & CD34..n0.5..CD33 < 0.7275 & CD34 >= 0.63 & FS..n0.25..HLA_DR >= 4.58125)
Ind86 = which(SS..n0.75..CD13 >= 1.85625 & CD33..n0.33..CD13 >= 2.20166666666667 & SS..n0.75..CD117 >= 2.02125 & CD45..n0.25..CD33 < 3.19875 & CD33..n0.67..CD13 >= 1.11166666666667 & CD33..a0.33..CD13 >= 3.49 & FS..n0.75..CD34 >= 2.60375 & CD34..n0.5..CD33 < 0.7925 & FS..n0.25..CD7 >= 3.44125 & CD45 < 4.235 & CD45..n0.67..CD33 >= -1.005 & FS..n0.25..CD117 >= 3.5625 & CD34..n0.5..CD33 >= 0.7275)
Ind87 = which(SS..n0.75..CD13 >= 1.85625 & CD33..n0.33..CD13 >= 2.20166666666667 & SS..n0.75..CD117 >= 2.02125 & CD45..n0.25..CD33 < 3.19875 & CD33..n0.67..CD13 >= 1.11166666666667 & CD33..a0.33..CD13 >= 3.49 & FS..n0.75..CD34 >= 2.60375 & CD34..n0.5..CD33 < 0.7925 & FS..n0.25..CD7 >= 3.44125 & CD45 >= 4.235)
Ind88 = which(SS..n0.75..CD13 >= 1.85625 & CD33..n0.33..CD13 >= 2.20166666666667 & SS..n0.75..CD117 >= 2.02125 & CD45..n0.25..CD33 < 3.19875 & CD33..n0.67..CD13 >= 1.11166666666667 & CD33..a0.33..CD13 >= 3.49 & FS..n0.75..CD34 >= 2.60375 & CD34..n0.5..CD33 >= 0.7925)
Ind89 = which(SS..n0.75..CD13 >= 1.85625 & CD33..n0.33..CD13 >= 2.20166666666667 & SS..n0.75..CD117 >= 2.02125 & CD45..n0.25..CD33 >= 3.19875)

RulePopNumber[Ind1] = 1
RulePopNumber[Ind10] = 10
RulePopNumber[Ind11] = 11
RulePopNumber[Ind12] = 12
RulePopNumber[Ind13] = 13
RulePopNumber[Ind14] = 14
RulePopNumber[Ind15] = 15
RulePopNumber[Ind16] = 16
RulePopNumber[Ind17] = 17
RulePopNumber[Ind18] = 18
RulePopNumber[Ind19] = 19
RulePopNumber[Ind2] = 2
RulePopNumber[Ind20] = 20
RulePopNumber[Ind21] = 21
RulePopNumber[Ind22] = 22
RulePopNumber[Ind23] = 23
RulePopNumber[Ind24] = 24
RulePopNumber[Ind25] = 25
RulePopNumber[Ind26] = 26
RulePopNumber[Ind27] = 27
RulePopNumber[Ind28] = 28
RulePopNumber[Ind29] = 29
RulePopNumber[Ind3] = 3
RulePopNumber[Ind30] = 30
RulePopNumber[Ind31] = 31
RulePopNumber[Ind32] = 32
RulePopNumber[Ind33] = 33
RulePopNumber[Ind34] = 34
RulePopNumber[Ind35] = 35
RulePopNumber[Ind36] = 36
RulePopNumber[Ind37] = 37
RulePopNumber[Ind38] = 38
RulePopNumber[Ind39] = 39
RulePopNumber[Ind4] = 4
RulePopNumber[Ind40] = 40
RulePopNumber[Ind41] = 41
RulePopNumber[Ind42] = 42
RulePopNumber[Ind43] = 43
RulePopNumber[Ind44] = 44
RulePopNumber[Ind45] = 45
RulePopNumber[Ind46] = 46
RulePopNumber[Ind47] = 47
RulePopNumber[Ind48] = 48
RulePopNumber[Ind49] = 49
RulePopNumber[Ind5] = 5
RulePopNumber[Ind50] = 50
RulePopNumber[Ind51] = 51
RulePopNumber[Ind52] = 52
RulePopNumber[Ind53] = 53
RulePopNumber[Ind54] = 54
RulePopNumber[Ind55] = 55
RulePopNumber[Ind56] = 56
RulePopNumber[Ind57] = 57
RulePopNumber[Ind58] = 58
RulePopNumber[Ind59] = 59
RulePopNumber[Ind6] = 6
RulePopNumber[Ind60] = 60
RulePopNumber[Ind61] = 61
RulePopNumber[Ind62] = 62
RulePopNumber[Ind63] = 63
RulePopNumber[Ind64] = 64
RulePopNumber[Ind65] = 65
RulePopNumber[Ind66] = 66
RulePopNumber[Ind67] = 67
RulePopNumber[Ind68] = 68
RulePopNumber[Ind69] = 69
RulePopNumber[Ind7] = 7
RulePopNumber[Ind70] = 70
RulePopNumber[Ind71] = 71
RulePopNumber[Ind72] = 72
RulePopNumber[Ind73] = 73
RulePopNumber[Ind74] = 74
RulePopNumber[Ind75] = 75
RulePopNumber[Ind76] = 76
RulePopNumber[Ind77] = 77
RulePopNumber[Ind78] = 78
RulePopNumber[Ind79] = 79
RulePopNumber[Ind8] = 8
RulePopNumber[Ind80] = 80
RulePopNumber[Ind81] = 81
RulePopNumber[Ind82] = 82
RulePopNumber[Ind83] = 83
RulePopNumber[Ind84] = 84
RulePopNumber[Ind85] = 85
RulePopNumber[Ind86] = 86
RulePopNumber[Ind87] = 87
RulePopNumber[Ind88] = 88
RulePopNumber[Ind89] = 89
RulePopNumber[Ind9] = 9
 
RuleCls[Ind1] = 1
RuleCls[Ind2] = 2
RuleCls[Ind3] = 1
RuleCls[Ind4] = 1
RuleCls[Ind5] = 2
RuleCls[Ind6] = 1
RuleCls[Ind7] = 1
RuleCls[Ind8] = 1
RuleCls[Ind9] = 1
RuleCls[Ind10] = 2
RuleCls[Ind11] = 1
RuleCls[Ind12] = 1
RuleCls[Ind13] = 1
RuleCls[Ind14] = 1
RuleCls[Ind15] = 1
RuleCls[Ind16] = 1
RuleCls[Ind17] = 1
RuleCls[Ind18] = 2
RuleCls[Ind19] = 1
RuleCls[Ind20] = 2
RuleCls[Ind21] = 2
RuleCls[Ind22] = 1
RuleCls[Ind23] = 2
RuleCls[Ind24] = 2
RuleCls[Ind25] = 2
RuleCls[Ind26] = 2
RuleCls[Ind27] = 2
RuleCls[Ind28] = 1
RuleCls[Ind29] = 2
RuleCls[Ind30] = 1
RuleCls[Ind31] = 2
RuleCls[Ind32] = 2
RuleCls[Ind33] = 1
RuleCls[Ind34] = 2
RuleCls[Ind35] = 1
RuleCls[Ind36] = 2
RuleCls[Ind37] = 2
RuleCls[Ind38] = 2
RuleCls[Ind39] = 1
RuleCls[Ind40] = 1
RuleCls[Ind41] = 2
RuleCls[Ind42] = 1
RuleCls[Ind43] = 2
RuleCls[Ind44] = 2
RuleCls[Ind45] = 1
RuleCls[Ind46] = 1
RuleCls[Ind47] = 2
RuleCls[Ind48] = 2
RuleCls[Ind49] = 1
RuleCls[Ind50] = 1
RuleCls[Ind51] = 1
RuleCls[Ind52] = 1
RuleCls[Ind53] = 1
RuleCls[Ind54] = 1
RuleCls[Ind55] = 2
RuleCls[Ind56] = 2
RuleCls[Ind57] = 2
RuleCls[Ind58] = 2
RuleCls[Ind59] = 1
RuleCls[Ind60] = 1
RuleCls[Ind61] = 1
RuleCls[Ind62] = 2
RuleCls[Ind63] = 1
RuleCls[Ind64] = 2
RuleCls[Ind65] = 1
RuleCls[Ind66] = 2
RuleCls[Ind67] = 2
RuleCls[Ind68] = 2
RuleCls[Ind69] = 1
RuleCls[Ind70] = 2
RuleCls[Ind71] = 2
RuleCls[Ind72] = 1
RuleCls[Ind73] = 2
RuleCls[Ind74] = 1
RuleCls[Ind75] = 2
RuleCls[Ind76] = 1
RuleCls[Ind77] = 1
RuleCls[Ind78] = 1
RuleCls[Ind79] = 1
RuleCls[Ind80] = 1
RuleCls[Ind81] = 1
RuleCls[Ind82] = 2
RuleCls[Ind83] = 1
RuleCls[Ind84] = 2
RuleCls[Ind85] = 1
RuleCls[Ind86] = 2
RuleCls[Ind87] = 2
RuleCls[Ind88] = 2
RuleCls[Ind89] = 2
 
Indlist = list(Ind1,Ind2,Ind3,Ind4,Ind5,Ind6,Ind7,Ind8,Ind9,Ind10,Ind11,Ind12,Ind13,Ind14,Ind15,Ind16,Ind17,Ind18,Ind19,Ind20,Ind21,Ind22,Ind23,Ind24,Ind25,Ind26,Ind27,Ind28,Ind29,Ind30,Ind31,Ind32,Ind33,Ind34,Ind35,Ind36,Ind37,Ind38,Ind39,Ind40,Ind41,Ind42,Ind43,Ind44,Ind45,Ind46,Ind47,Ind48,Ind49,Ind50,Ind51,Ind52,Ind53,Ind54,Ind55,Ind56,Ind57,Ind58,Ind59,Ind60,Ind61,Ind62,Ind63,Ind64,Ind65,Ind66,Ind67,Ind68,Ind69,Ind70,Ind71,Ind72,Ind73,Ind74,Ind75,Ind76,Ind77,Ind78,Ind79,Ind80,Ind81,Ind82,Ind83,Ind84,Ind85,Ind86,Ind87,Ind88,Ind89)
return(list(RuleCls=RuleCls,PopulationNumber=RulePopNumber,IndList=Indlist))
}