ALPODSclassifier = function(Data,Header,Type="V2"){
# [RuleCls,PopulationNumber] = MRcinderellaALPODSClassify(Data,Header)
# rule based classifier and subpopulations corresponding to RuleCls
# INPUT
# Data(1:d,1:n)        data array of d cases with n variables
# Header(1:n,:)        array of variable names
# OUTPUT
# RuleCls[1:d)             vector of classes, d integer numbers, number k indicates class k
# PopulationNumber[1:d)    vector of classes, d integer numbers, number i indicates subpopulation  i
#
# V 1.4 generated by XAI ALPODS in matlab
#
if(Type=="V1"){#MRcinderellaALPODSClassify
V=dim(Data); n = V[1]; d = V[2]; 
RuleCls = zeros(n,1)
 PopulationNumber =zeros(n,1)
CD117=findAttrCol('CD117',Header,Data)
CD13=findAttrCol('CD13',Header,Data)
CD33=findAttrCol('CD33',Header,Data)
CD34=findAttrCol('CD34',Header,Data)
CD45=findAttrCol('CD45',Header,Data)
CD56=findAttrCol('CD56',Header,Data)
CD7=findAttrCol('CD7',Header,Data)
FS=findAttrCol('FS',Header,Data)
HLA_DR=findAttrCol('HLA_DR',Header,Data)
SS=findAttrCol('SS',Header,Data)
Ind1001 =which((CD45 < 3.8745) &(CD33 >= 3.4335))
 RuleCls[Ind1001] = 1 
 PopulationNumber[Ind1001] = 1
Ind1002 =which((HLA_DR >= 2.3525) &(SS < 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind1002] = 1 
 PopulationNumber[Ind1002] = 32
Ind1003 =which((CD13 < 3.9335) &(CD45 >= 3.8745) &(CD33 >= 3.4335))
 RuleCls[Ind1003] = 1 
 PopulationNumber[Ind1003] = 7
Ind1005 =which((CD117 >= 2.5515) &(HLA_DR < 2.3525) &(SS < 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind1005] = 1 
 PopulationNumber[Ind1005] = 52
Ind1007 =which((CD34 >= 2.8305) &(CD13 >= 3.5675) &(CD45 < 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind1007] = 1 
 PopulationNumber[Ind1007] = 28
Ind1008 =which((CD34 < 2.2005) &(HLA_DR < 2.6375) &(CD45 >= 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind1008] = 1 
 PopulationNumber[Ind1008] = 27
Ind1009 =which((CD34 < 2.1585) &(HLA_DR >= 2.6375) &(CD45 >= 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind1009] = 1 
 PopulationNumber[Ind1009] = 40
Ind1010 =which((CD117 >= 2.6945) &(HLA_DR >= 2.6525) &(CD13 >= 3.9335) &(CD45 >= 3.8745) &(CD33 >= 3.4335))
 RuleCls[Ind1010] = 1 
 PopulationNumber[Ind1010] = 33
Ind1011 =which((CD33 >= 2.7915) &(FS < 5.7055) &(CD13 < 3.5675) &(CD45 < 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind1011] = 1 
 PopulationNumber[Ind1011] = 21
Ind1012 =which((CD13 < 2.9745) &(FS >= 5.7055) &(CD13 < 3.5675) &(CD45 < 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind1012] = 1 
 PopulationNumber[Ind1012] = 4
Ind1013 =which((CD34 >= 3.0995) &(CD34 >= 2.1585) &(HLA_DR >= 2.6375) &(CD45 >= 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind1013] = 1 
 PopulationNumber[Ind1013] = 42
Ind1014 =which((CD45 < 4.0395) &(CD117 < 2.6945) &(HLA_DR >= 2.6525) &(CD13 >= 3.9335) &(CD45 >= 3.8745) &(CD33 >= 3.4335))
 RuleCls[Ind1014] = 1 
 PopulationNumber[Ind1014] = 20
Ind1015 =which((HLA_DR >= 3.2605) &(CD33 < 2.7915) &(FS < 5.7055) &(CD13 < 3.5675) &(CD45 < 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind1015] = 1 
 PopulationNumber[Ind1015] = 45
Ind1018 =which((FS >= 5.8375) &(CD34 < 2.5165) &(CD34 < 2.8305) &(CD13 >= 3.5675) &(CD45 < 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind1018] = 1 
 PopulationNumber[Ind1018] = 17
Ind1020 =which((CD13 < 3.8185) &(CD45 < 3.8955) &(CD34 >= 2.2005) &(HLA_DR < 2.6375) &(CD45 >= 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind1020] = 1 
 PopulationNumber[Ind1020] = 37
Ind1025 =which((HLA_DR < 3.0125) &(CD33 >= 2.8945) &(CD13 >= 2.9745) &(FS >= 5.7055) &(CD13 < 3.5675) &(CD45 < 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind1025] = 1 
 PopulationNumber[Ind1025] = 9
Ind1028 =which((CD117 >= 2.628) &(SS < 5.8635) &(CD34 >= 2.5165) &(CD34 < 2.8305) &(CD13 >= 3.5675) &(CD45 < 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind1028] = 1 
 PopulationNumber[Ind1028] = 54
Ind1030 =which((CD13 < 3.6495) &(FS >= 6.0035) &(CD34 < 3.0995) &(CD34 >= 2.1585) &(HLA_DR >= 2.6375) &(CD45 >= 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind1030] = 1 
 PopulationNumber[Ind1030] = 48
Ind1033 =which((CD117 >= 2.4705) &(SS >= 4.9005) &(HLA_DR < 3.2605) &(CD33 < 2.7915) &(FS < 5.7055) &(CD13 < 3.5675) &(CD45 < 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind1033] = 1 
 PopulationNumber[Ind1033] = 44
Ind1035 =which((CD34 < 2.2585) &(FS < 5.8675) &(FS < 6.0035) &(CD34 < 3.0995) &(CD34 >= 2.1585) &(HLA_DR >= 2.6375) &(CD45 >= 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind1035] = 1 
 PopulationNumber[Ind1035] = 34
Ind1036 =which((CD13 < 3.5955) &(FS >= 5.8675) &(FS < 6.0035) &(CD34 < 3.0995) &(CD34 >= 2.1585) &(HLA_DR >= 2.6375) &(CD45 >= 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind1036] = 1 
 PopulationNumber[Ind1036] = 38
Ind1039 =which((CD13 >= 4.3735) &(CD34 >= 2.2585) &(FS < 5.8675) &(FS < 6.0035) &(CD34 < 3.0995) &(CD34 >= 2.1585) &(HLA_DR >= 2.6375) &(CD45 >= 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind1039] = 1 
 PopulationNumber[Ind1039] = 50
Ind1040 =which((CD13 >= 4.3885) &(CD13 >= 3.5955) &(FS >= 5.8675) &(FS < 6.0035) &(CD34 < 3.0995) &(CD34 >= 2.1585) &(HLA_DR >= 2.6375) &(CD45 >= 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind1040] = 1 
 PopulationNumber[Ind1040] = 31
Ind1042 =which((SS >= 6.0095) &(CD56 < 2.8735) &(FS >= 5.7595) &(HLA_DR >= 2.7375) &(CD45 >= 4.0395) &(CD117 < 2.6945) &(HLA_DR >= 2.6525) &(CD13 >= 3.9335) &(CD45 >= 3.8745) &(CD33 >= 3.4335))
 RuleCls[Ind1042] = 1 
 PopulationNumber[Ind1042] = 30
Ind1044 =which((CD7 >= 2.4665) &(CD45 < 3.1175) &(CD117 < 2.4705) &(SS >= 4.9005) &(HLA_DR < 3.2605) &(CD33 < 2.7915) &(FS < 5.7055) &(CD13 < 3.5675) &(CD45 < 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind1044] = 1 
 PopulationNumber[Ind1044] = 41
Ind1046 =which((CD117 >= 2.9865) &(FS < 5.8515) &(FS < 5.9915) &(CD34 >= 2.3395) &(CD13 < 4.4175) &(CD45 >= 3.8955) &(CD34 >= 2.2005) &(HLA_DR < 2.6375) &(CD45 >= 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind1046] = 1 
 PopulationNumber[Ind1046] = 53
Ind1047 =which((CD13 < 3.7115) &(FS >= 5.8515) &(FS < 5.9915) &(CD34 >= 2.3395) &(CD13 < 4.4175) &(CD45 >= 3.8955) &(CD34 >= 2.2005) &(HLA_DR < 2.6375) &(CD45 >= 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind1047] = 1 
 PopulationNumber[Ind1047] = 51
Ind1050 =which((CD117 >= 2.7905) &(CD13 < 4.3735) &(CD34 >= 2.2585) &(FS < 5.8675) &(FS < 6.0035) &(CD34 < 3.0995) &(CD34 >= 2.1585) &(HLA_DR >= 2.6375) &(CD45 >= 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind1050] = 1 
 PopulationNumber[Ind1050] = 49
Ind1052 =which((SS >= 5.9025) &(CD45 < 3.9795) &(CD13 < 4.3885) &(CD13 >= 3.5955) &(FS >= 5.8675) &(FS < 6.0035) &(CD34 < 3.0995) &(CD34 >= 2.1585) &(HLA_DR >= 2.6375) &(CD45 >= 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind1052] = 1 
 PopulationNumber[Ind1052] = 35
Ind1054 =which((CD45 >= 4.2285) &(CD45 >= 3.9795) &(CD13 < 4.3885) &(CD13 >= 3.5955) &(FS >= 5.8675) &(FS < 6.0035) &(CD34 < 3.0995) &(CD34 >= 2.1585) &(HLA_DR >= 2.6375) &(CD45 >= 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind1054] = 1 
 PopulationNumber[Ind1054] = 47
Ind2004 =which((CD117 < 2.5515) &(HLA_DR < 2.3525) &(SS < 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind2004] = 2 
 PopulationNumber[Ind2004] = 2
Ind2006 =which((HLA_DR < 2.6525) &(CD13 >= 3.9335) &(CD45 >= 3.8745) &(CD33 >= 3.4335))
 RuleCls[Ind2006] = 2 
 PopulationNumber[Ind2006] = 6
Ind2016 =which((CD33 < 2.8945) &(CD13 >= 2.9745) &(FS >= 5.7055) &(CD13 < 3.5675) &(CD45 < 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind2016] = 2 
 PopulationNumber[Ind2016] = 24
Ind2017 =which((FS < 5.8375) &(CD34 < 2.5165) &(CD34 < 2.8305) &(CD13 >= 3.5675) &(CD45 < 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind2017] = 2 
 PopulationNumber[Ind2017] = 25
Ind2019 =which((SS >= 5.8635) &(CD34 >= 2.5165) &(CD34 < 2.8305) &(CD13 >= 3.5675) &(CD45 < 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind2019] = 2 
 PopulationNumber[Ind2019] = 23
Ind2021 =which((CD13 >= 3.8185) &(CD45 < 3.8955) &(CD34 >= 2.2005) &(HLA_DR < 2.6375) &(CD45 >= 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind2021] = 2 
 PopulationNumber[Ind2021] = 14
Ind2022 =which((CD13 >= 4.4175) &(CD45 >= 3.8955) &(CD34 >= 2.2005) &(HLA_DR < 2.6375) &(CD45 >= 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind2022] = 2 
 PopulationNumber[Ind2022] = 29
Ind2023 =which((HLA_DR < 2.7375) &(CD45 >= 4.0395) &(CD117 < 2.6945) &(HLA_DR >= 2.6525) &(CD13 >= 3.9335) &(CD45 >= 3.8745) &(CD33 >= 3.4335))
 RuleCls[Ind2023] = 2 
 PopulationNumber[Ind2023] = 36
Ind2024 =which((SS < 4.9005) &(HLA_DR < 3.2605) &(CD33 < 2.7915) &(FS < 5.7055) &(CD13 < 3.5675) &(CD45 < 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind2024] = 2 
 PopulationNumber[Ind2024] = 16
Ind2026 =which((HLA_DR >= 3.0125) &(CD33 >= 2.8945) &(CD13 >= 2.9745) &(FS >= 5.7055) &(CD13 < 3.5675) &(CD45 < 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind2026] = 2 
 PopulationNumber[Ind2026] = 46
Ind2027 =which((CD117 < 2.628) &(SS < 5.8635) &(CD34 >= 2.5165) &(CD34 < 2.8305) &(CD13 >= 3.5675) &(CD45 < 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind2027] = 2 
 PopulationNumber[Ind2027] = 12
Ind2029 =which((CD34 < 2.3395) &(CD13 < 4.4175) &(CD45 >= 3.8955) &(CD34 >= 2.2005) &(HLA_DR < 2.6375) &(CD45 >= 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind2029] = 2 
 PopulationNumber[Ind2029] = 19
Ind2031 =which((CD13 >= 3.6495) &(FS >= 6.0035) &(CD34 < 3.0995) &(CD34 >= 2.1585) &(HLA_DR >= 2.6375) &(CD45 >= 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind2031] = 2 
 PopulationNumber[Ind2031] = 10
Ind2032 =which((FS < 5.7595) &(HLA_DR >= 2.7375) &(CD45 >= 4.0395) &(CD117 < 2.6945) &(HLA_DR >= 2.6525) &(CD13 >= 3.9335) &(CD45 >= 3.8745) &(CD33 >= 3.4335))
 RuleCls[Ind2032] = 2 
 PopulationNumber[Ind2032] = 43
Ind2034 =which((FS >= 5.9915) &(CD34 >= 2.3395) &(CD13 < 4.4175) &(CD45 >= 3.8955) &(CD34 >= 2.2005) &(HLA_DR < 2.6375) &(CD45 >= 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind2034] = 2 
 PopulationNumber[Ind2034] = 22
Ind2037 =which((CD56 >= 2.8735) &(FS >= 5.7595) &(HLA_DR >= 2.7375) &(CD45 >= 4.0395) &(CD117 < 2.6945) &(HLA_DR >= 2.6525) &(CD13 >= 3.9335) &(CD45 >= 3.8745) &(CD33 >= 3.4335))
 RuleCls[Ind2037] = 2 
 PopulationNumber[Ind2037] = 39
Ind2038 =which((CD45 >= 3.1175) &(CD117 < 2.4705) &(SS >= 4.9005) &(HLA_DR < 3.2605) &(CD33 < 2.7915) &(FS < 5.7055) &(CD13 < 3.5675) &(CD45 < 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind2038] = 2 
 PopulationNumber[Ind2038] = 26
Ind2041 =which((SS < 6.0095) &(CD56 < 2.8735) &(FS >= 5.7595) &(HLA_DR >= 2.7375) &(CD45 >= 4.0395) &(CD117 < 2.6945) &(HLA_DR >= 2.6525) &(CD13 >= 3.9335) &(CD45 >= 3.8745) &(CD33 >= 3.4335))
 RuleCls[Ind2041] = 2 
 PopulationNumber[Ind2041] = 18
Ind2043 =which((CD7 < 2.4665) &(CD45 < 3.1175) &(CD117 < 2.4705) &(SS >= 4.9005) &(HLA_DR < 3.2605) &(CD33 < 2.7915) &(FS < 5.7055) &(CD13 < 3.5675) &(CD45 < 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind2043] = 2 
 PopulationNumber[Ind2043] = 13
Ind2045 =which((CD117 < 2.9865) &(FS < 5.8515) &(FS < 5.9915) &(CD34 >= 2.3395) &(CD13 < 4.4175) &(CD45 >= 3.8955) &(CD34 >= 2.2005) &(HLA_DR < 2.6375) &(CD45 >= 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind2045] = 2 
 PopulationNumber[Ind2045] = 3
Ind2048 =which((CD13 >= 3.7115) &(FS >= 5.8515) &(FS < 5.9915) &(CD34 >= 2.3395) &(CD13 < 4.4175) &(CD45 >= 3.8955) &(CD34 >= 2.2005) &(HLA_DR < 2.6375) &(CD45 >= 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind2048] = 2 
 PopulationNumber[Ind2048] = 8
Ind2049 =which((CD117 < 2.7905) &(CD13 < 4.3735) &(CD34 >= 2.2585) &(FS < 5.8675) &(FS < 6.0035) &(CD34 < 3.0995) &(CD34 >= 2.1585) &(HLA_DR >= 2.6375) &(CD45 >= 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind2049] = 2 
 PopulationNumber[Ind2049] = 5
Ind2051 =which((SS < 5.9025) &(CD45 < 3.9795) &(CD13 < 4.3885) &(CD13 >= 3.5955) &(FS >= 5.8675) &(FS < 6.0035) &(CD34 < 3.0995) &(CD34 >= 2.1585) &(HLA_DR >= 2.6375) &(CD45 >= 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind2051] = 2 
 PopulationNumber[Ind2051] = 15
Ind2053 =which((CD45 < 4.2285) &(CD45 >= 3.9795) &(CD13 < 4.3885) &(CD13 >= 3.5955) &(FS >= 5.8675) &(FS < 6.0035) &(CD34 < 3.0995) &(CD34 >= 2.1585) &(HLA_DR >= 2.6375) &(CD45 >= 3.8245) &(SS >= 4.7305) &(CD33 < 3.4335))
 RuleCls[Ind2053] = 2 
 PopulationNumber[Ind2053] = 11
# end Classifier: MRcinderellaALPODSClassify()
V=list(RuleCls,PopulationNumber)
names(V) = c('RuleCls','PopulationNumber')
return(V)
}
        
if(Type=="V2"){#MTcinderellaALPODSClassify
        # [RuleCls,PopulationNumber] = MTcinderellaALPODSClassify(Data,Header)
        # rule based classifier and subpopulations corresponding to RuleCls
        # INPUT
        # Data(1:d,1:n)        data array of d cases with n variables
        # Header(1:n,:)        array of variable names
        # OUTPUT
        # RuleCls[1:d)             vector of classes, d integer numbers, number k indicates class k
        # PopulationNumber[1:d)    vector of classes, d integer numbers, number i indicates subpopulation  i
        #
        # V 1.4
        #
        V=dim(Data); n = V[1]; d = V[2]; 
        RuleCls = zeros(n,1)
        PopulationNumber =zeros(n,1)
        CD13=findAttrCol('CD13',Header,Data)
        CD33=findAttrCol('CD33',Header,Data)
        CD34=findAttrCol('CD34',Header,Data)
        CD45=findAttrCol('CD45',Header,Data)
        CD56=findAttrCol('CD56',Header,Data)
        CD7=findAttrCol('CD7',Header,Data)
        FS=findAttrCol('FS',Header,Data)
        HLA_DR=findAttrCol('HLA_DR',Header,Data)
        SS=findAttrCol('SS',Header,Data)
        Ind1001 =which((CD33 >= 3.7545) &(CD34 < 2.4475))
        RuleCls[Ind1001] = 1 
        PopulationNumber[Ind1001] = 5
        Ind1003 =which((HLA_DR < 2.3605) &(CD45 >= 1.8695) &(CD33 < 3.7545) &(CD34 < 2.4475))
        RuleCls[Ind1003] = 1 
        PopulationNumber[Ind1003] = 1
        Ind1004 =which((FS < 5.5215) &(CD13 < 3.8915) &(FS < 5.8145) &(CD34 >= 2.4475))
        RuleCls[Ind1004] = 1 
        PopulationNumber[Ind1004] = 4
        Ind1005 =which((HLA_DR < 2.9215) &(CD13 >= 3.8915) &(FS < 5.8145) &(CD34 >= 2.4475))
        RuleCls[Ind1005] = 1 
        PopulationNumber[Ind1005] = 8
        Ind1007 =which((CD45 < 3.2545) &(FS >= 5.5215) &(CD13 < 3.8915) &(FS < 5.8145) &(CD34 >= 2.4475))
        RuleCls[Ind1007] = 1 
        PopulationNumber[Ind1007] = 38
        Ind1008 =which((CD33 >= 3.9505) &(HLA_DR < 2.6345) &(CD13 < 3.8025) &(FS >= 5.8145) &(CD34 >= 2.4475))
        RuleCls[Ind1008] = 1 
        PopulationNumber[Ind1008] = 34
        Ind1011 =which((CD45 < 3.6005) &(CD33 < 3.3545) &(HLA_DR >= 2.3605) &(CD45 >= 1.8695) &(CD33 < 3.7545) &(CD34 < 2.4475))
        RuleCls[Ind1011] = 1 
        PopulationNumber[Ind1011] = 12
        Ind1012 =which((CD45 >= 3.7485) &(CD33 >= 3.3545) &(HLA_DR >= 2.3605) &(CD45 >= 1.8695) &(CD33 < 3.7545) &(CD34 < 2.4475))
        RuleCls[Ind1012] = 1 
        PopulationNumber[Ind1012] = 20
        Ind1014 =which((CD45 < 3.2855) &(CD33 < 3.9505) &(HLA_DR < 2.6345) &(CD13 < 3.8025) &(FS >= 5.8145) &(CD34 >= 2.4475))
        RuleCls[Ind1014] = 1 
        PopulationNumber[Ind1014] = 16
        Ind1015 =which((SS >= 5.9965) &(CD33 < 3.6495) &(HLA_DR >= 2.6345) &(CD13 < 3.8025) &(FS >= 5.8145) &(CD34 >= 2.4475))
        RuleCls[Ind1015] = 1 
        PopulationNumber[Ind1015] = 30
        Ind1016 =which((CD33 >= 4.0425) &(CD33 >= 3.6495) &(HLA_DR >= 2.6345) &(CD13 < 3.8025) &(FS >= 5.8145) &(CD34 >= 2.4475))
        RuleCls[Ind1016] = 1 
        PopulationNumber[Ind1016] = 23
        Ind1017 =which((SS < 5.7785) &(CD33 >= 3.5295) &(CD45 < 3.9585) &(CD13 >= 3.8025) &(FS >= 5.8145) &(CD34 >= 2.4475))
        RuleCls[Ind1017] = 1 
        PopulationNumber[Ind1017] = 25
        Ind1019 =which((CD33 >= 3.5405) &(HLA_DR < 3.0905) &(CD45 >= 3.9585) &(CD13 >= 3.8025) &(FS >= 5.8145) &(CD34 >= 2.4475))
        RuleCls[Ind1019] = 1 
        PopulationNumber[Ind1019] = 15
        Ind1021 =which((CD34 < 2.3145) &(CD45 < 3.7485) &(CD33 >= 3.3545) &(HLA_DR >= 2.3605) &(CD45 >= 1.8695) &(CD33 < 3.7545) &(CD34 < 2.4475))
        RuleCls[Ind1021] = 1 
        PopulationNumber[Ind1021] = 28
        Ind1022 =which((SS >= 5.2675) &(CD45 >= 3.5155) &(CD45 >= 3.2545) &(FS >= 5.5215) &(CD13 < 3.8915) &(FS < 5.8145) &(CD34 >= 2.4475))
        RuleCls[Ind1022] = 1 
        PopulationNumber[Ind1022] = 19
        Ind1024 =which((CD45 >= 3.8345) &(CD45 >= 3.2855) &(CD33 < 3.9505) &(HLA_DR < 2.6345) &(CD13 < 3.8025) &(FS >= 5.8145) &(CD34 >= 2.4475))
        RuleCls[Ind1024] = 1 
        PopulationNumber[Ind1024] = 35
        Ind1025 =which((CD56 < 2.3325) &(SS < 5.9965) &(CD33 < 3.6495) &(HLA_DR >= 2.6345) &(CD13 < 3.8025) &(FS >= 5.8145) &(CD34 >= 2.4475))
        RuleCls[Ind1025] = 1 
        PopulationNumber[Ind1025] = 7
        Ind1026 =which((CD45 >= 3.7085) &(CD33 < 4.0425) &(CD33 >= 3.6495) &(HLA_DR >= 2.6345) &(CD13 < 3.8025) &(FS >= 5.8145) &(CD34 >= 2.4475))
        RuleCls[Ind1026] = 1 
        PopulationNumber[Ind1026] = 29
        Ind1028 =which((CD45 >= 4.0285) &(CD33 < 3.5405) &(HLA_DR < 3.0905) &(CD45 >= 3.9585) &(CD13 >= 3.8025) &(FS >= 5.8145) &(CD34 >= 2.4475))
        RuleCls[Ind1028] = 1 
        PopulationNumber[Ind1028] = 17
        Ind1029 =which((CD7 >= 3.9395) &(CD56 < 3.0565) &(CD45 >= 3.6005) &(CD33 < 3.3545) &(HLA_DR >= 2.3605) &(CD45 >= 1.8695) &(CD33 < 3.7545) &(CD34 < 2.4475))
        RuleCls[Ind1029] = 1 
        PopulationNumber[Ind1029] = 40
        Ind1030 =which((CD45 < 3.2435) &(CD34 >= 2.3145) &(CD45 < 3.7485) &(CD33 >= 3.3545) &(HLA_DR >= 2.3605) &(CD45 >= 1.8695) &(CD33 < 3.7545) &(CD34 < 2.4475))
        RuleCls[Ind1030] = 1 
        PopulationNumber[Ind1030] = 43
        Ind1032 =which((HLA_DR >= 3.181) &(SS < 5.2675) &(CD45 >= 3.5155) &(CD45 >= 3.2545) &(FS >= 5.5215) &(CD13 < 3.8915) &(FS < 5.8145) &(CD34 >= 2.4475))
        RuleCls[Ind1032] = 1 
        PopulationNumber[Ind1032] = 39
        Ind1033 =which((CD45 < 3.6405) &(CD56 >= 2.3325) &(SS < 5.9965) &(CD33 < 3.6495) &(HLA_DR >= 2.6345) &(CD13 < 3.8025) &(FS >= 5.8145) &(CD34 >= 2.4475))
        RuleCls[Ind1033] = 1 
        PopulationNumber[Ind1033] = 26
        Ind1034 =which((CD45 < 3.3865) &(CD45 < 3.7085) &(CD33 < 4.0425) &(CD33 >= 3.6495) &(HLA_DR >= 2.6345) &(CD13 < 3.8025) &(FS >= 5.8145) &(CD34 >= 2.4475))
        RuleCls[Ind1034] = 1 
        PopulationNumber[Ind1034] = 41
        Ind1036 =which((FS < 5.3645) &(CD7 < 3.9395) &(CD56 < 3.0565) &(CD45 >= 3.6005) &(CD33 < 3.3545) &(HLA_DR >= 2.3605) &(CD45 >= 1.8695) &(CD33 < 3.7545) &(CD34 < 2.4475))
        RuleCls[Ind1036] = 1 
        PopulationNumber[Ind1036] = 42
        Ind1038 =which((CD45 >= 3.5615) &(CD45 >= 3.2435) &(CD34 >= 2.3145) &(CD45 < 3.7485) &(CD33 >= 3.3545) &(HLA_DR >= 2.3605) &(CD45 >= 1.8695) &(CD33 < 3.7545) &(CD34 < 2.4475))
        RuleCls[Ind1038] = 1 
        PopulationNumber[Ind1038] = 22
        Ind1040 =which((CD34 >= 2.6985) &(CD45 >= 3.6405) &(CD56 >= 2.3325) &(SS < 5.9965) &(CD33 < 3.6495) &(HLA_DR >= 2.6345) &(CD13 < 3.8025) &(FS >= 5.8145) &(CD34 >= 2.4475))
        RuleCls[Ind1040] = 1 
        PopulationNumber[Ind1040] = 37
        Ind1043 =which((CD45 >= 3.8705) &(CD7 < 2.8195) &(FS >= 5.3645) &(CD7 < 3.9395) &(CD56 < 3.0565) &(CD45 >= 3.6005) &(CD33 < 3.3545) &(HLA_DR >= 2.3605) &(CD45 >= 1.8695) &(CD33 < 3.7545) &(CD34 < 2.4475))
        RuleCls[Ind1043] = 1 
        PopulationNumber[Ind1043] = 33
        Ind2002 =which((CD45 < 1.8695) &(CD33 < 3.7545) &(CD34 < 2.4475))
        RuleCls[Ind2002] = 2 
        PopulationNumber[Ind2002] = 13
        Ind2006 =which((HLA_DR >= 2.9215) &(CD13 >= 3.8915) &(FS < 5.8145) &(CD34 >= 2.4475))
        RuleCls[Ind2006] = 2 
        PopulationNumber[Ind2006] = 36
        Ind2009 =which((CD33 < 3.5295) &(CD45 < 3.9585) &(CD13 >= 3.8025) &(FS >= 5.8145) &(CD34 >= 2.4475))
        RuleCls[Ind2009] = 2 
        PopulationNumber[Ind2009] = 3
        Ind2010 =which((HLA_DR >= 3.0905) &(CD45 >= 3.9585) &(CD13 >= 3.8025) &(FS >= 5.8145) &(CD34 >= 2.4475))
        RuleCls[Ind2010] = 2 
        PopulationNumber[Ind2010] = 6
        Ind2013 =which((CD45 < 3.5155) &(CD45 >= 3.2545) &(FS >= 5.5215) &(CD13 < 3.8915) &(FS < 5.8145) &(CD34 >= 2.4475))
        RuleCls[Ind2013] = 2 
        PopulationNumber[Ind2013] = 31
        Ind2018 =which((SS >= 5.7785) &(CD33 >= 3.5295) &(CD45 < 3.9585) &(CD13 >= 3.8025) &(FS >= 5.8145) &(CD34 >= 2.4475))
        RuleCls[Ind2018] = 2 
        PopulationNumber[Ind2018] = 18
        Ind2020 =which((CD56 >= 3.0565) &(CD45 >= 3.6005) &(CD33 < 3.3545) &(HLA_DR >= 2.3605) &(CD45 >= 1.8695) &(CD33 < 3.7545) &(CD34 < 2.4475))
        RuleCls[Ind2020] = 2 
        PopulationNumber[Ind2020] = 32
        Ind2023 =which((CD45 < 3.8345) &(CD45 >= 3.2855) &(CD33 < 3.9505) &(HLA_DR < 2.6345) &(CD13 < 3.8025) &(FS >= 5.8145) &(CD34 >= 2.4475))
        RuleCls[Ind2023] = 2 
        PopulationNumber[Ind2023] = 2
        Ind2027 =which((CD45 < 4.0285) &(CD33 < 3.5405) &(HLA_DR < 3.0905) &(CD45 >= 3.9585) &(CD13 >= 3.8025) &(FS >= 5.8145) &(CD34 >= 2.4475))
        RuleCls[Ind2027] = 2 
        PopulationNumber[Ind2027] = 14
        Ind2031 =which((HLA_DR < 3.181) &(SS < 5.2675) &(CD45 >= 3.5155) &(CD45 >= 3.2545) &(FS >= 5.5215) &(CD13 < 3.8915) &(FS < 5.8145) &(CD34 >= 2.4475))
        RuleCls[Ind2031] = 2 
        PopulationNumber[Ind2031] = 24
        Ind2035 =which((CD45 >= 3.3865) &(CD45 < 3.7085) &(CD33 < 4.0425) &(CD33 >= 3.6495) &(HLA_DR >= 2.6345) &(CD13 < 3.8025) &(FS >= 5.8145) &(CD34 >= 2.4475))
        RuleCls[Ind2035] = 2 
        PopulationNumber[Ind2035] = 11
        Ind2037 =which((CD45 < 3.5615) &(CD45 >= 3.2435) &(CD34 >= 2.3145) &(CD45 < 3.7485) &(CD33 >= 3.3545) &(HLA_DR >= 2.3605) &(CD45 >= 1.8695) &(CD33 < 3.7545) &(CD34 < 2.4475))
        RuleCls[Ind2037] = 2 
        PopulationNumber[Ind2037] = 21
        Ind2039 =which((CD34 < 2.6985) &(CD45 >= 3.6405) &(CD56 >= 2.3325) &(SS < 5.9965) &(CD33 < 3.6495) &(HLA_DR >= 2.6345) &(CD13 < 3.8025) &(FS >= 5.8145) &(CD34 >= 2.4475))
        RuleCls[Ind2039] = 2 
        PopulationNumber[Ind2039] = 27
        Ind2041 =which((CD7 >= 2.8195) &(FS >= 5.3645) &(CD7 < 3.9395) &(CD56 < 3.0565) &(CD45 >= 3.6005) &(CD33 < 3.3545) &(HLA_DR >= 2.3605) &(CD45 >= 1.8695) &(CD33 < 3.7545) &(CD34 < 2.4475))
        RuleCls[Ind2041] = 2 
        PopulationNumber[Ind2041] = 9
        Ind2042 =which((CD45 < 3.8705) &(CD7 < 2.8195) &(FS >= 5.3645) &(CD7 < 3.9395) &(CD56 < 3.0565) &(CD45 >= 3.6005) &(CD33 < 3.3545) &(HLA_DR >= 2.3605) &(CD45 >= 1.8695) &(CD33 < 3.7545) &(CD34 < 2.4475))
        RuleCls[Ind2042] = 2 
        PopulationNumber[Ind2042] = 10
        # end Classifier: MTcinderellaALPODSClassify()
        V=list(RuleCls,PopulationNumber)
        names(V) = c('RuleCls','PopulationNumber')
        return(V)
}else{
  message("V1 or V2 are possible choices")
  return("V1 or V2 are possible choices")
}

}